### ISSUE TITLE
Image not supported (?)

### ISSUE THREAD

**Issue by JeanCollas** [JimBobSquarePants/ImageSharp#104]
I encounter some issues with some specific images, I don't really understand why, could you help me? :)
It is a quite simple use:

                Image image = new Image(ms);
                MemoryStream ms = new MemoryStream();
                await file.CopyToAsync(ms);

For example this image:
https://github.com/JeanCollas/Upload/blob/master/Amy.jpg

I use the latest of master branch, and reference following ImageSharp projects:
base, 
Drawing,
Drawing.Paths,
Bmp,
Gif,
Jpeg,
Png,
Processing

in Decode, header variable of size 16 is full of '0'

                format = this.Configuration.ImageFormats.FirstOrDefault(x => x.IsSupportedFileFormat(header));

returns null, but contains 4 entries (bmp,gif,jpeg and png).

**Comment by tocsoft** [comment]
you are currently giving the `Image` class an empty `MemoryStream` it has nothing to decode.

The latest builds would allow you to create an image directly from a file path. i.e. 
```c#
// requires netstandard1.3+ compatible run-time
using(Image image = new Image('file/path.png'))
{
    // do stuff with the image in here
}
```

or if you want to continue to use the stream apis you will want to do 

```c#
MemoryStream ms = new MemoryStream();
await file.CopyToAsync(ms);
ms.Position = 0; // reset stream to start position
using(Image image = new Image(ms))
{
    // do stuff with the image in here
}
```

or more likely you would just want to do if you already have a file stream to save you form the copy (as ImageSharp internally take a copy of the image data and doesn't require the stream to remain after the constructor has complete.)
```c#
using(Image image = new Image(file)) // assuming file is a FileStream who's lifetime is managed seperatly
{
    // do stuff with the image in here
}
```

For performance reasons you will want to make sure you always dispose of `Image`s once you are done with them.

**Comment by JeanCollas** [comment]
Yes, thanks, I just figured it out by going deeper in the code! 
I was missing the 'ms.Position = 0;'

I get the file from a web form, so the file may not be the right option ;)

**Comment by tocsoft** [comment]
glad to help
