### ISSUE TITLE
"No image formats have been configured" exception throw.

### ISSUE THREAD

**Issue by ZhiqiangTao** [JimBobSquarePants/ImageSharp#105]
I use the code below:

byte[] image = HttpHelper.HttpGetImage("http://xxxx/xxx.jpg", "");
Image obj = new Image(image);
var width = obj.Width;
var height = obj.Height;

but the exception will throw out while new an Image instance by using the byte[].
What' the problem? How to fix it?

**Comment by antonfirsov** [comment]
@ZhiqiangTao
- Make sure you are using the newest [official MyGet](https://www.myget.org/gallery/imagesharp) packages
- Image formats live in separate packages. Make sure you are referencing `ImageSharp.Formats.Jpeg`
- When posting an issue, do not remove the issue template, it's here for a reason

**Comment by tocsoft** [comment]
you need to reference one or more of the `ImageSharp.Formats.XXX` pacakges.
