### ISSUE TITLE
PngDecoder: ImageFormatException: Image stream is not valid

### ISSUE THREAD

**Issue by chrisvandijk** [JimBobSquarePants/ImageSharp#115]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have another png file which causes the following error:

ImageSharp.ImageFormatException: Image stream is not valid!
   at ImageSharp.Formats.PngDecoderCore.ReadChunkLength(PngChunk chunk)
   at ImageSharp.Formats.PngDecoderCore.ReadChunk()
   at ImageSharp.Formats.PngDecoderCore.Decode[TColor](Image`1 image, Stream stream)
   at ImageSharp.Image`1.Decode(Stream stream)
   at ImageSharp.Image`1.Load(Stream stream)

### Steps to Reproduce
Try to open the following file:
![Error image](https://content.cvdsoftware.nl/errors/a0361d72d87b84a84ccf30482821e692856b8118.png)

Resaved with Fireworks (works OK):
![Resaved and OK](https://content.cvdsoftware.nl/errors/a0361d72d87b84a84ccf30482821e692856b8118-fw.png)
### System Configuration
- ImageSharp version: 1.0.0-alpha2-00090
- Other ImageSharp packages and versions: ImageSharp.Formats.Png: 1.0.0-alpha2-00086
- Environment (Operating system, version and so on): Windows 10 Pro x64
- .NET Framework version: .NET Core 1.1.0, NETStandard 1.6.1

**Comment by JimBobSquarePants** [comment]
Thanks for the info. Give the latest version (1.0.0-alpha2-00111) a pop.
