### ISSUE TITLE
Consider adding a Metapackage to ImageSharp.Formats

### ISSUE THREAD

**Issue by Bartmax** [JimBobSquarePants/ImageSharp#116]
Do you consider making a metapackage (ImageSharps.Formats) that have a dependency on ImageSharp.Formats.Png/Jpg, etc. For ease of installation in those scenarios that we want all available file formats to work with ?

**Comment by JimBobSquarePants** [comment]
Hi @Bartmax. This is a better fit for a discussion in Gitter. Could we continue it there please instead?

**Comment by Bartmax** [comment]
Got no chance to talk to you on gitter but just updated the packages and I wanted to say that right now is way better! Good job on reducing the amount of packages needed.

**Comment by JimBobSquarePants** [comment]
Cheers! Yeah much better.
