### ISSUE TITLE
Png Decode ''CRC Error. PNG Image chunk is corrupt"

### ISSUE THREAD

**Issue by vinhhrv** [JimBobSquarePants/ImageSharp#127]
I am try load this png image, but somthing wrong, how to by pass this error.
Image display oke

Png Decode ''CRC Error. PNG Image chunk is corrupt"

![bug_png](https://cloud.githubusercontent.com/assets/769541/23692986/7d714472-0404-11e7-9594-70ddb848dc6a.png)

Sori if my english not good

**Comment by blackcity** [comment]
Checked with TweakPNG. The image is corrupt:
<img width="353" alt="crc" src="https://cloud.githubusercontent.com/assets/4624420/23701427/fb82b070-03f6-11e7-9ec5-b3d8948b5ce8.PNG">

**Comment by JimBobSquarePants** [comment]
@blackcity Thanks for investigating. 👍 

I had a look also using PngAnalyzer which was able to decode the image as can windows itself which suggests to me that the default behaviour of most decoders is to jump out as soon a we hi the end marker.

I've changed the code to do the same. The image now decodes properly.

**Comment by vinhhrv** [comment]
@JimBobSquarePants thank you
