### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by taumuon** [JimBobSquarePants/ImageSharp#128]
Hi,

I'm new to .net core and am having trouble building the solution, it's not really an issue with this project but I wonder if you could help?

I have VS 2015 and VS2017 installed. I opened the solution and let VS2017 upgrade, but it doesn't build.

Instead, I navigated to the src directory
and
dotnet build
builds successfully

in the test folder
dotnet test
seems to work but takes forever

dotnet test -c Release
doesn't work - all the projects have "warnings as errors" set to true, and there are warnings due to copyright formats.

Maybe the 2017 upgrade inserted this into the projects?

I could continue fighting through this, but was wondering what the best workflow is to work with the code?

Thanks,
gary

**Comment by tocsoft** [comment]
The solution isn't in a state where the auto migration will work for it out of the box and it needs a cleanup pass before it will work... we plan to migrate the solution over to the new VS 2017 project formats soon but until we have performed the upgrade then you should use VS 2015 if you want to run the project locally.
