### ISSUE TITLE
The specified CGI application encountered an error and the server terminated the process

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#13]
_From @Bartmax on September 6, 2016 0:50_

When resizing multiple big images on aspnet core i usually get:

```
The specified CGI application encountered an error and the server terminated the process
```

is there anything I can do to mitigate this?

_Copied from original issue: JimBobSquarePants/ImageProcessor#467_

**Comment by JimBobSquarePants** [comment]
No idea. I'm going to need waaaaay more information than that.

**Comment by JimBobSquarePants** [comment]
_From @Bartmax on September 6, 2016 1:19_

What kind of information?
This happens on azure standard-size machine. It doesn't on local machine, and I can repro if I choose to resize ~7 images of about ~20mb each to a resolution of 600px width (keeping aspect) that ends in about ~45kb. (just an example). Almost any time-consuming resize process returns that error.

The resize does happen and after that (since I cache the resized images) the site works with no prob.

It looks like a timeout of some sorts.

**Comment by JimBobSquarePants** [comment]
Are those images 20MB each compressed or do you mean in memory?
How long are they individually taking?

If the resize is actually taking place then you might be on track. It sounds like there is some sort of response timeout taking place which would be in the realms of the ASP team to instruct you on working around. It can't be an imageprocessor specific issue since no exceptions are thrown by the library and we are successfully encoding.

I haven't actually used ASP.NET Core yet so I'm not going to be much help I'm afraid.

**Comment by JimBobSquarePants** [comment]
_From @Bartmax on September 6, 2016 12:49_

@JimBobSquarePants 20mb compressed.
Each image takes a considerable amount of time. don't know exactly how much
I will try to investigate a little further and then cross reference to the aspnet team.
I'll let you know if I discover something.

**Comment by JimBobSquarePants** [comment]
Thanks!

**Comment by JimBobSquarePants** [comment]
Hey @Bartmax have you seen this come up again recently? We've been doing some serious memory and performance optimisation in the repo.

**Comment by Bartmax** [comment]
I have an environment that I can repo this easily but I need 3-4 days to get into it. I'll let you know.

**Comment by JimBobSquarePants** [comment]
Thanks. Is this with the latest codebase? I can't think why it would be us but I'd like to be sure.

**Comment by Bartmax** [comment]
This is ASP.NET. I filled an issue here:
https://github.com/aspnet/Home/issues/1857

**Comment by JimBobSquarePants** [comment]
Ah excellent work recreating the issue without the library! I think we should close this here then really since it's not specific to ImageSharp.

**Comment by mho00** [comment]
I got this when sent requests to Azure API app as fast as I could from console application.  Slowing sending down (adding 50ms sleep) ended errors.
