### ISSUE TITLE
Use C#7 ref returns for indexers

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#134]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I want to take advantage of the new C#7 features available to us now we have made the switch to VS2017. A major one being ref returns and locals.  

https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/

This would allow us to avoid ugly code like 

``` csharp
TColor d = default(TColor);
d.PackFromVector4(destination);
firstPassPixels[x, y] = d;
```

replacing it with code like 

``` csharp
ref TColor d = ref firstPassPixels[x, y];
d.PackFromVector4(destination);
```

Theoretically we should be able to use ref returns and locals to improve the performance of the application throughout. I'll create a WIP PR for us to collaborate on to keep each other right.

**Comment by antonfirsov** [comment]
What about non-C#7 users? Will they be able to consume indexers on PixelAccessor?
I'm really curious if the code change above brings in any speedup. We need a (non-nano) benchmark to emulate the "pack-from-refreturns"  (and purely that!) scenario, informing us about the effects of this microoptimization technique.
I also want to work on the resize code soon. I want to replace the first-pass pixelaccessor with a PinnedBuffer of Vector4-s here!

**Comment by JimBobSquarePants** [comment]
>What about non-C#7 users? Will they be able to consume indexers on PixelAccessor?

As far as I understand they can yes, they just get the value-type as normal. I think... 

>I also want to work on the resize code soon. I want to replace the first-pass pixelaccessor with a PinnedBuffer of Vector4-s here!

Absolutely, I've not started on the work and want to ensure we have designed benchmarks etc before any implementation. Let's do resize first.

**Comment by antonfirsov** [comment]
> As far as I understand they can yes, they just get the value-type as normal. I think...

How about setters? Haven't researched this topic yet, not sure if everything works as we expect. Fun fact: array indexers are implemented as ref returns from the very beginning (!), but its a languge-level hack.

**Comment by JimBobSquarePants** [comment]
You've given me the fear now. Sound's like we'd have to make the indexer internal and use public get/set methods.

**Comment by JimBobSquarePants** [comment]
The more I think about this the more I don't like it. There's places we can use ref local but not here.

**Comment by antonfirsov** [comment]
@JimBobSquarepants check out my idea on octree optimization ;)

**Comment by JimBobSquarePants** [comment]
@antonfirsov Oh yeah?! Where is it

**Comment by antonfirsov** [comment]
I have made a quite detailed response on #130. Really need your feedback :)
