### ISSUE TITLE
Memroy growing and not release!

### ISSUE THREAD

**Issue by ZhiqiangTao** [JimBobSquarePants/ImageSharp#136]
I'm using asp.net core with 1.0.3 sdk to work.
Now, I have a problem as below:
1. there are many many pics on the web interface.
2. HttpClient is used to download each pic from the interface. like(for(int i=0, i<pics.Length, i++))
3. just one thing i need to do is get the pic's width and height, so i use below code to get the property.
  
```
   byte[] imageBytes = HttpHelper.HttpGetImage(scene.src_url, "");
   scene.bytes = imageBytes.Length;
    using (**ImageSharp.Image** obj = new **ImageSharp.Image**(imageBytes))
     {
                    scene.width = obj.Width;
                    scene.height = obj.Height;
                    scene.bit_depth = 0;
       }
```

4. now I found that the memory used is very very large, I use the Diagnosis tool（vs2017）to get the snapshot and try to find the large object which not release! I found as below:
```
    DefaultArrayPool+Bucket<ImageSharp.Formats.Jpg.DecodedBlock>	17(reference count)	219,280,752(byte)	219,280,752(byte)
    DefaultArrayPool+Bucket<ImageSharp.Color>	  	                        27    79,180,640	79,180,640    
    DefaultArrayPool+Bucket<Byte>	                                                        31	31,463,072	31,463,072     
```
I found that the ImageSharp's objects use **the most of the memory**。

5. Notice that, the memory is still not be released after the application stops work!
6. i try to use"GC.Collect()" to release the memory, but no significant change of the memory. the 
 ImageSharp's objects still use **the most of the memory**。

who can give me some useful info for that.

**Comment by JimBobSquarePants** [comment]
@ZhiqiangTao Soooooooo.......

**Comment by KLuuKer** [comment]
@JimBobSquarePants  He is complaining about the ArrayPool not releasing memory

**Comment by antonfirsov** [comment]
@ZhiqiangTao see answers on #123
