### ISSUE TITLE
DrawText(...) add TextGraphicOptions to force a consistent pixel height per point

### ISSUE THREAD

**Issue by tocsoft** [JimBobSquarePants/ImageSharp#148]
We need to add a new property to `TextGraphicOptions` `PointsAsPixels` which will cause the point size passed into the `DrawText(...)` as part of the font to draw at a consistent pixel size instead of being image dpi dependent.

Effectively this will just override the dpi passed into the `SixLabors.Fonts.TextRenderer` so instead of using the images option it uses a hard coded value.

**Comment by tocsoft** [comment]
due to the fact that `TextGraphicOptions`  is a struct I've gone with a property called `UseImageResolution` to toggle this feature on or off. the invert was required due to the fact that bools default to true in structs and I wanted to ensure that feature was enabled by default.

**Comment by JimBobSquarePants** [comment]
Bowing down to your experience here but I'm assuming that's what most other libraries do by default?

**Comment by tocsoft** [comment]
The few I've looked over seem to.

**Comment by JimBobSquarePants** [comment]
Cool. I'm good with that then 👍
