### ISSUE TITLE
Can't just write exif data (and preserve the original image)

### ISSUE THREAD

**Issue by kensan73** [JimBobSquarePants/ImageSharp#150]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

As a consumer of ImageSharp
When I modify exif data (via image.MetaData.ExifProfile.SetVAlue)
And then call image.Save();
Then I expect to see an option besides subsample and quality
So that I can just save out the original image
### Steps to Reproduce

Here's the code I am running

            const string source = Root + "1.jpg";
            var dest = Root + Guid.NewGuid() + ".TryUseBitmap_THISDOESNTWORKATALL" + "exif.jpg";

            using (ImageSharp.Image image = new ImageSharp.Image(source))
            {
                var copyright = image.MetaData.ExifProfile.GetValue(ExifTag.Copyright);
                image.MetaData.ExifProfile.SetValue(ExifTag.Copyright, "ken OrE");
//                image.Save(source, null); // new JpegEncoder { Subsample = JpegSubsample.Ratio444, Quality = 100});
                image.Save(source, new JpegEncoder { Subsample = JpegSubsample.Ratio444, Quality = 100});
            }

### System Configuration

Windows

- ImageSharp version: 1.0.0-alpha2-00058
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: Dotnet Core
- Additional information:

And apologies in advance, there's no discussion groups or an email or documentation that I can find.  I have opened the code and don't see any shortcircuits to not encode.

Thanks for any help!

**Comment by JimBobSquarePants** [comment]
Hi @kensan73, 

The discussion group - [Gitter](https://gitter.im/ImageSharp/General) is actually mentioned in the main repo readme and in the [contribution guidelines](https://github.com/JimBobSquarePants/ImageSharp/blob/master/.github/CONTRIBUTING.md) that would have popped up when you created the issue. 

Let's move the conversation to there to start with.

Cheers 

James
