### ISSUE TITLE
ImageSharp csproj targets net standard 1.1 and 1.3 at the same time

### ISSUE THREAD

**Issue by vpenades** [JimBobSquarePants/ImageSharp#153]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of ImageSharp
- [x ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I was trying to include imagesharp into a Net.Framework Console application and it refused to reference the project, after a simple review I found the csproj is wrong:

[(TargetFrameworks)netstandard1.3;netstandard1.1(/TargetFrameworks)](https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/ImageSharp.csproj#L7)

Which I think is wrong and should point to netstandard1.3 only (drawing project too!)

### Steps to Reproduce

create a net framework console project and try to reference imagesharp instance

### System Configuration

- ImageSharp version: latest
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): w10
- .NET Framework version: Net Framework 4.6.2
- Additional information:

**Comment by antonfirsov** [comment]
This is intentional:
Basically, we target 1.1 to access the widest possible range of platform implementations, while explicitly targeting newer platforms (like 1.3) let's us to provide [API-s which could not be provided with 1.1](https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/Image/Image%7BTColor%7D.cs#L134)
