### ISSUE TITLE
Guetzli JPEG encoder

### ISSUE THREAD

**Issue by vinhhrv** [JimBobSquarePants/ImageSharp#161]
Hi ImageSharp,

Can you support Guetzli encoder for JPEG  ?,

"Google reduces JPEG file size by 35%"

https://github.com/google/guetzli/

Thank you

**Comment by NelsonFord** [comment]
Yeah, just bought a brandnew C64. Would be great if my image fits into memory. But, wait, how long does it take to encode? Shit: https://github.com/google/guetzli/issues/50

If you find any irony, keep it. :smile:

**Comment by antonfirsov** [comment]
@NelsonFord the decoded image is not a Jpeg in the memory any longer, it's smaller only in the HDD.

@vinhhrv Guetzli is not a general-case Jpeg encoder, it is for users who can invest large amount of CPU work to make their images smaller. We don't have plans to implement such feature at the moment. 

Also, please use [our gitter channel](gitter.im/ImageSharp/General) to discuss these kinds of quick ideas. See our [contribuiton guide](https://github.com/JimBobSquarePants/ImageSharp/blob/master/.github/CONTRIBUTING.md)!
