### ISSUE TITLE
Saving image as png with quality and compression increase the size and make the background transparent

### ISSUE THREAD

**Issue by mhamri** [JimBobSquarePants/ImageSharp#163]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
save an image as png increase the size 
using compression ration is damaging the quality

### Steps to Reproduce
[this](http://www.photobook.com.my/media/catalog/product/cache/1/image/800x/040ec09b1e35df139433887a97daa66f/l/f/lf-mlh_1.jpg) is the image that i'm using which has 149kB size

```
public Stream SetImage(Stream file, int? qualityRate, int? compressRate){
    var fileStream = new MemoryStream();
    
    using (var client = new ImageSharp.Image(file))
    {
        var pngEncoderOptions = new PngEncoderOptions()
        {
            //Quantizer = new WuQuantizer<Color>(),
            IgnoreMetadata = true
        };

        if (qualityRate != null)
        {
            pngEncoderOptions.Quality = (int)qualityRate;
        }
        if  compressRate != null)
        {
            pngEncoderOptions.CompressionLevel = (int compressRate;
        }
        client.SaveAsPng(fileStream, pngEncoderOptions);
    }

    return fileStream;
}

```
as you can see i commented out the Quantizer here, i will post the result with different Quantizer in bellow, just imagine the Quantizer is oCtree or Wu

WuQuantizer- quality 100 - compression 9 : the result is **183KB**
![q100c9](https://cloud.githubusercontent.com/assets/8991783/24687810/62cb7a5c-19ee-11e7-84f2-5f28c75f8674.png)

WuQuantizer- quality 200 - compression:9 : the result is **206KB**
![q200c9](https://cloud.githubusercontent.com/assets/8991783/24687824/7d46c814-19ee-11e7-97a8-be28870a6248.png)

without Quantizer(default Quantizer)- quality: 200 - compression : 9 the result is : **206KB**
![q200c9-without](https://cloud.githubusercontent.com/assets/8991783/24687894/f02d79fe-19ee-11e7-9d5c-ef25ff78cd22.png)

as you can see after conversion the picture is loosing the background and it become transparent. if i see it in a image viewer without transparency support like windows image viewer the image look fine, but it's not the case for web.

![q200c9-without-appear](https://cloud.githubusercontent.com/assets/8991783/24687995/adbf8264-19ef-11e7-9086-6e7086a02e75.png)

my benchmark is [tinypng](https://tinypng.com/). it compress the same image to **86.9KB**
![lf-mlh_1 1](https://cloud.githubusercontent.com/assets/8991783/24688085/44e391bc-19f0-11e7-9b52-1baaa607aaad.jpg)

I don't know anything about PNG decode and encode to help with the code. but if you through me some good document about it i can read and help with the implementation in my leisuer time. 

again thanks for great work

### System Configuration
- ImageSharp version: 1.0.0-alpha4-00043
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): windows
- .NET Framework version: asp.net core, .netcore 1.1

**Comment by JimBobSquarePants** [comment]
Hi @mhamri 

Can you please update to the most recent version 1.0.0-alpha5-00047and let me know what the output is like?

Cheers

James

**Comment by JimBobSquarePants** [comment]
@mhamri You should be able to update your version now and get the correct output.
