### ISSUE TITLE
alpha channel being corrupted/set when encoding png in `Palette` (Quality == 256) mode

### ISSUE THREAD

**Issue by tocsoft** [JimBobSquarePants/ImageSharp#165]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When encoding a png without any additional options except setting `image.MetaData.Quality = 256;` then decoding the image again we end up with an image with a transparency set which isn't in the original.

### Steps to Reproduce
```c#
        [Theory]
        [WithSolidFilledImages(100, 100, 126, 0, 0, PixelTypes.StandardImageClass)]
        public void CanSaveIndexedPng<TColor>(TestImageProvider<TColor> provider)
            where TColor : struct, IPixel<TColor>
        {
            // does saving a file then repoening mean both files are identical???
            using (Image<TColor> image = provider.GetImage())
            using (MemoryStream ms = new MemoryStream())
            {
                image.MetaData.Quality = 256;
                image.Save(ms, new PngEncoder());
                ms.Position = 0;
                image.DebugSave(provider, extension: "png");

                using (Image<TColor> img2 = Image.Load<TColor>(ms, new PngDecoder()))
                {
                    img2.DebugSave(provider, new { decoded = true }, extension: "png");

                    using (PixelAccessor<TColor> accessor1 = image.Lock())
                    using (PixelAccessor<TColor> accessor2 = img2.Lock())
                    {
                        for (int y = 0; y < image.Height; y++)
                        {
                            for (int x = 0; x < image.Width; x++)
                            {
                                Assert.Equal(accessor1[x, y], accessor2[x, y]);
                            }
                        }
                    }
                }
            }
        }
```
### System Configuration

- ImageSharp version: (master branch) f91d6b513da93fb09158487abd9c61d0d2a64592
- Other ImageSharp packages and versions: n/a
- Environment (Operating system, version and so on): win 10
- .NET Framework version: coreclr
- Additional information: n/a

**Comment by tocsoft** [comment]
note the reason you will need to run the test using the `PixelAccessor` is because there is a bug in `ImageComparer.CheckSimilarity(expected, actual);` which means its basically just not working unless all pixels are different, I've fixed that but in doing so discovered this one.

**Comment by JimBobSquarePants** [comment]
Weird... Working on this just now. I can see the problem just not sure how to avoid it. 

See #163

**Comment by JimBobSquarePants** [comment]
Should be fixed now.
