### ISSUE TITLE
Off by one Issue decoding indexed png

### ISSUE THREAD

**Issue by tocsoft** [JimBobSquarePants/ImageSharp#166]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Another png issue, when decoding an index png the pixels seem to be off by one when its resaved.

## Source image
![before](https://cloud.githubusercontent.com/assets/166440/24709960/85ea6186-1a13-11e7-8283-3428880c17ac.png)

## Index encoded image
![cansaveindexedpng_standardimageclass_testpattern100x100](https://cloud.githubusercontent.com/assets/166440/24710117/0b59b5a6-1a14-11e7-8efe-f36f92459c74.png)

## After decoding
This is generated by opening the indexed png then encoded it back back as a bmp (converted to png using MS paint as github doesn't support bmp files)
![after](https://cloud.githubusercontent.com/assets/166440/24709950/7ce200b2-1a13-11e7-8129-59cd42031485.png)

### Steps to Reproduce

```c#
        [Theory]
        [WithTestPatternImages(100, 100, PixelTypes.StandardImageClass)]
        public void CanSaveIndexedPng<TColor>(TestImageProvider<TColor> provider)
            where TColor : struct, IPixel<TColor>
        {
            // does saving a file then repoening mean both files are identical???
            using (Image<TColor> image = provider.GetImage())
            using (MemoryStream ms = new MemoryStream())
            {
                image.MetaData.Quality = 256;
                image.Save(ms, new PngEncoder());
                ms.Position = 0;
                image.DebugSave(provider, extension: "bmp");

                using (Image<TColor> img2 = Image.Load<TColor>(ms, new PngDecoder()))
                {
                    img2.Save(provider, new { decoded = true }, extension: "bmp");

                    using (PixelAccessor<TColor> accessor1 = image.Lock())
                    using (PixelAccessor<TColor> accessor2 = img2.Lock())
                    {
                        for (int y = 0; y < image.Height; y++)
                        {
                            for (int x = 0; x < image.Width; x++)
                            {
                                Assert.Equal(accessor1[x, y], accessor2[x, y]);
                            }
                        }
                    }
                }
            }
        }
```
### System Configuration

- ImageSharp version: (master branch) f91d6b5
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
![kitty-whack-a-mole1](https://cloud.githubusercontent.com/assets/385879/24731302/72c66a0c-1aac-11e7-998b-7d5c9c74fdae.gif)
