### ISSUE TITLE
Issue referencing in .net core

### ISSUE THREAD

**Issue by eat-sleep-code** [JimBobSquarePants/ImageSharp#19]
Is this the replacement for ImageProcessor.Core?

I installed this using nuget and it states it is version 0.0.0.0

Before, I would reference it with _Using ImageProcessor_ but this reference doesn't appear to work?

**Comment by dlemstra** [comment]
Yes this is the library that replaces ImageProcessor.Core. The NuGet package was published to reserve the namespace (see: https://www.nuget.org/packages/ImageSharp/). You should use the MyGet repository (https://www.myget.org/gallery/imagesharp) if you want to use the latest development build of this project.

The name has also changed so you should be `using ImageSharp` instead now.

**Comment by eat-sleep-code** [comment]
Ok, makes sense.   https://www.myget.org/gallery/imagesharp causes errors in Visual Studio (it tries to find all my MS packages under that URL)   I believe I need a different path?

**Comment by dlemstra** [comment]
The page (https://www.myget.org/gallery/imagesharp) contains a button 'Connect to feed' that will give you the proper URL.

**Comment by eat-sleep-code** [comment]
Thanks.

**Comment by DMWOO7** [comment]
It may be noted that Visual Studio seems to prefer its own package source (api.nuget.org). So when you install it using the command-line, it will fetch the package from there. I changed the order in the settings (NuGet package manager > packet sources) to have the myget one at the top. But NuGet use still its official one. 

The solution is to use NuGet GUI (right click on the project > *Manage NuGet packages*). In the right corner you can choose which package source should be used. Select your added MyGet one, check *include advance version* and you can install the `ImageShape `package from MyGet. Using the official NuGet package didn't work for me, there exist no namespace for the `Image` class.
