### ISSUE TITLE
Applying blur to image's rectangle clearing pixels around provided rectangle

### ISSUE THREAD

**Issue by agoretsky** [JimBobSquarePants/ImageSharp#194]
### Description
I use this code:
```
            using (var image = Image.Load(@"in.jpg"))
            {
                image.GaussianBlur(3, new Rectangle(660, 110, 200, 200));

                image.Save("test.png");
            }
```
and I expect that it should just blur an area on image, but it clearing all area around rectangle. Is it right behavior?

![in](https://cloud.githubusercontent.com/assets/17613086/25490241/e4c14fb8-2b74-11e7-9f6b-403fb3d35640.jpg)

![test](https://cloud.githubusercontent.com/assets/17613086/25490257/ecdeafba-2b74-11e7-95fd-f22371ac1416.png)

**Comment by dlemstra** [comment]
That is not the correct behavior, the other pixels should be preserved. And please don't delete the issue template next time. Now we don't know which version you have used.
