### ISSUE TITLE
Review all ImageProcessors where buffer swapping occurs to ensure data isn't lost when using rects

### ISSUE THREAD

**Issue by tocsoft** [JimBobSquarePants/ImageSharp#197]
In some `ImageProcessor<TPixel>` we create a new target `PixelAcessor<TPixel>` that we write to be for finally calling   `source.SwapPixelsBuffers(targetPixels);` to swap the pixel buffers back into the souce image object.

We need to identify instances where we do this to ensure we don't end up loosing pixel data that isn;t in the target rectangle.

The simplest fix for this could be a simple as adding
```c#
if (!source.Bounds.Equals(sourceRectangle))
{
    sourcePixels.CopyTo(targetPixels);
}
``` 
after instantiating the target area. Alternatively in some cases it might actually be enough to just over write the source area directly but that will need to determined on a case be cases bases.

**Comment by JimBobSquarePants** [comment]
I should be able to identify most of these pretty quickly. I'd much rather remove the new target when it's not needed than do the check, much less allocations.

**Comment by JimBobSquarePants** [comment]
Done with #195

I want to sort out our tests now though. Our tests approach for testing the filters is inconsistent.
