### ISSUE TITLE
Saving gif gives wrong\missing pallet colors

### ISSUE THREAD

**Issue by KLuuKer** [JimBobSquarePants/ImageSharp#199]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This original image
![original-gif](https://cloud.githubusercontent.com/assets/12729178/25539327/01a019c0-2c47-11e7-97d5-ed200d9f34dc.gif)

when saving turns into this
![bad-gif](https://cloud.githubusercontent.com/assets/12729178/25539333/07c40a8c-2c47-11e7-958c-803514209082.gif)

looks like a color pallet issue

### Steps to Reproduce
```C#
Image.Load("original-gif.gif").Save("bad-gif.gif");
```

### System Configuration

- ImageSharp version: 1.0.0-alpha7-0031
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): win10 x64
- .NET Framework version: netcoreapp1.0 and net461
- Additional information:

**Comment by JimBobSquarePants** [comment]
Oh wow, that's nasty! Will have a look asap.

**Comment by JimBobSquarePants** [comment]
Just waiting on a PR review for this one.

**Comment by KLuuKer** [comment]
Confirmed fixed, thank you very much
