### ISSUE TITLE
Measuring text?

### ISSUE THREAD

**Issue by Daniel15** [JimBobSquarePants/ImageSharp#204]
I'm wondering whether it's possible to measure text using ImageSharp? I'm trying to replace some code that uses [Drawing.MeasureString from System.Graphics](https://msdn.microsoft.com/en-us/library/6xe5hazb(v=vs.110).aspx).

I tried searching Google for "imagesharp measure text" and also tried searching this repo, but didn't see anything relevant.

**Comment by JimBobSquarePants** [comment]
Hi @Daniel15 

See http://sixlabors.com/2017/04/08/watermarks/ for information on text measuring.

We will get decent documentation out as soon as we can to make finding info easier. We're just utterly swamped now getting the library in shape to launch the first beta.

Hope the example all makes sense.

Cheers

James

**Comment by Daniel15** [comment]
Thanks for the example! It looks very useful :)

**Comment by Daniel15** [comment]
I just tried it out and it works wonderfully! Thank you so much @JimBobSquarePants 😃 

I saw in #6 that there's plans to have API docs. Is there a staging website available to see work-in-progress docs? I'd be happy reading through auto-generated API docs even if they're incomplete.

**Comment by JimBobSquarePants** [comment]
That's great to hear!

We're building docs using Wyam in our feature/docs branch - You can build them locally using the instructions found here

https://wyam.io/docs/usage/command-line

The one's in the repo just now are completely unfinished and will change quite dramatically; The API docs do generate though. I'm actually, this second, working on them.

**Comment by vanhouc** [comment]
For anyone else here looking for an answer to text measuring. The example provided above can be found [here](https://github.com/SixLabors/Samples/tree/master/ImageSharp/DrawWaterMarkOnImage) since it appears that blog post no longer exists

**Comment by xfischer** [comment]
Thanks @vanhouc, more direct answer : 
```csharp
var font = SixLabors.Fonts.SystemFonts.CreateFont("Arial", 12);
TextMeasurer.Measure("YOUR TEXT", new RendererOptions(font));
```

**Comment by ibrahimozgon** [comment]
Thank you, 
most recent one :) 
`var fontSize = TextMeasurer.Measure("your Text", new TextOptions(font));
fontSize.Width`
