### ISSUE TITLE
Remove non-generic Image class

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#208]
Opening this issue to track the removal of the non-generic Image class from the API. 

The issue as it stands. 

While this works and is simple to follow. 

```
using (Image image = Image.Load("foo.jpg"))
{
    image.Resize(image.Width / 2, image.Height / 2)
         .Save("bar.jpg"); 
}
```

The following will not compile since we cannot implicitly cast from `Image<Rgba32>` to `Image` and all our methods return `Image<TPixel>`

```
using (Image image = Image.Load("foo.jpg"))
{
    Image image2 = image.Resize(image.Width / 2, image.Height / 2);
}
```
It's infeasible to create overloads where we cast, not just due to the maintenance workload but for the performance implications also so the best bet is to simply remove the class.

I don't consider generics to be a blocker. Linq is hugely popular.

**Comment by antonfirsov** [comment]
Unfortunately the pixel type (`Argb32`) is a noise for most of the server-side users, however it should not be an issue, because people are usually going with `var`.

With a static, `Argb32`-specific `Image` class, the following code should keep compiling:
```C#
using (var image = Image.Load("foo.jpg"))
{
    image.Resize(image.Width / 2, image.Height / 2)
         .Save("bar.jpg"); 
}
```

PS: @JimBobSquarePants I know this is not your favorite argument, but still true 😄

**Comment by JimBobSquarePants** [comment]
😄 Yeah true but hey still clunky! Generics all the way baby!

**Comment by tocsoft** [comment]
Just want to capture this too. When this is done we have some places in ImageSharp.Drawing that have a similar pattern, we have various Brushes, and a Pen class that should also be removed at the same time.
