### ISSUE TITLE
Xamarin Mobile support

### ISSUE THREAD

**Issue by ktngoykalolo** [JimBobSquarePants/ImageSharp#21]
Please integrate xamarin support out of the box.

**Comment by JimBobSquarePants** [comment]
I don't understand what you mean. According to this blog post Xamarin should be able to consume net standard libraries. https://blog.xamarin.com/net-standard-library-support-for-xamarin/

**Comment by ktngoykalolo** [comment]
my question should be wether this library will support Xamarin out of the box. 
I will check out that post. I see that you are a contributor to Magick.NET.

**Comment by JimBobSquarePants** [comment]
It's netstandard 1.1 which Xamarin should support

https://github.com/JimBobSquarePants/ImageSharp/blob/7b2897600e152d8bdc41d23b10ee69d04223158f/src/ImageSharp/project.json#L51
