### ISSUE TITLE
Out of Memory Exception when encoding certain ICC profiles.

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#217]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Decoding and encoding this image in RELEASE mode throws the following exception. In DEBUG it works fine.

![sample](https://cloud.githubusercontent.com/assets/385879/26086383/9a7ee6c8-3a2d-11e7-94dc-5e1ce4547780.jpg)

```
Message: System.OutOfMemoryException : Array dimensions exceeded supported range.

List`1.set_Capacity(int32 value)
List`1.Add(T item)
IccWriter.WriteTagData(IccDtatWriter writer, List`1 entries)
```
The last item in the StackTrace can be found [here](https://github.com/JimBobSquarePants/ImageSharp/blob/4ddcd816f2d630336091443ff98892ea74fe9273/src/ImageSharp/MetaData/Profiles/ICC/IccWriter.cs#L77)

### Steps to Reproduce

The following code should be enough to reproduce the error.

``` c#
using (var image = Image.Load("sample.jpg"))
{
    image.Save("sample1.jpg");
}
```

This is really weird. There's nothing in our code as far as I can see that would cause this issue. It fails every single time in RELEASE and works every time in DEBUG.

### System Configuration
- ImageSharp version: 1.0.0-alpha9-00052	
- Other ImageSharp packages and versions: NA
- Environment (Operating system, version and so on): Windows 10

**Comment by dlemstra** [comment]
Something weird is happening I do some poor man debugging:

```C#
IccTagDataEntry[] items = inData.Where(t => inData[0].Equals(t)).ToArray();
if (items.Length == 0)
{
    throw new System.NotImplementedException(string.Join("\n", inData.Select(t => t.Signature.ToString() + "_" + t.TagSignature.ToString())));
}
```

If I do a break instead the test passes. Off to work now, I hope this will help you further.

**Comment by dlemstra** [comment]
I am guessing that there is a funky Equals overload in one of the entries here: https://github.com/JimBobSquarePants/ImageSharp/tree/023cce36aee5d8bd26de17cf131afbb8f1bef3ba/src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries

**Comment by JimBobSquarePants** [comment]
I think you might be correct. There's a mix here of `IEquatable<T>` and inheritance plus only `Equals(object)` is only implemented in the base classes. As far as I know you should only implement it on sealed classes and always do both `Equals(object)` and `GetHashCode()`

**Comment by JimBobSquarePants** [comment]
Bravo @dlemstra you were bang on the money. It took me a few hours but I fixed the `IEquatable` implementation to work properly with inheritance.

**Comment by JimBobSquarePants** [comment]
@dlemstra @JBildstein One thing I have noticed since I refactored the inheritance to work is that there appears to be more ICC data coming out than going in. Any idea what could cause it?

**Comment by JimBobSquarePants** [comment]
Think I've fixed it with the last commit.

**Comment by JBildstein** [comment]
good to hear that you were able to resolve it. The equality of the TagDataEntries was something I wanted to discuss with you but I have to admit that I forgot.
The issue with more data going is very likely related to that. An ICC profile can reuse the data for multiple entries and finding out if an entry is the same is done with Equals. I assume that some entries don't appear equal even if they are, so the data is written multiple times.
I think there is also some potential for optimization by reading it only once and reusing the same instance but I'll have to check that again.

**Comment by JimBobSquarePants** [comment]
@JBildstein It does appear to vary from image to image. Definitely worth looking into. We should get the ball rolling with color transforms based on the profile also. Today I learned that WIC doesn't preserve the profile it just performs the change based on it.
