### ISSUE TITLE
Combine Images in Asp.net Core

### ISSUE THREAD

**Issue by ibneadam** [JimBobSquarePants/ImageSharp#218]
I am not sure if I am doing the right thing but I am trying to combine two images in asp.net core using ImageSharp.

`var image1=Image.Load(filePath);`
`var img = Image.Load(filePath);`
`image1.DrawImage(img, 1, new Size(img.Width, img.Height), new Point(200, 0)).Save(outputPath);`

I am getting following exception:

`Message = "Could not load type 'ImageSharp.Memory.Buffer1' from assembly 'ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."`

Can you please provide some documentation how can I combine the images or fix this bug?
Thanks!

**Comment by JimBobSquarePants** [comment]
Can you resubmit the issue please. This time with the template filled in properly. How are we supposed to know what version of Core, ImageSharp or anything you are using?

**Comment by ibneadam** [comment]
Updated to latest in Myget and now got it working, thanks!
