### ISSUE TITLE
TypeLoadException for Type ImageSharp.Rgba32 while resize in .NET Core 2.0

### ISSUE THREAD

**Issue by dbeuchler** [JimBobSquarePants/ImageSharp#219]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Image cannot be resized on ASP.NET Core 2.0 Preview

### Steps to Reproduce
Create .net core 2.0 application and try to resize an image (loaded from stream).

### System Configuration
Windows 10 x64, .Net Core 2.0 Preview

- ImageSharp version: 1.0.0-alpha9-00054
- Other ImageSharp packages and versions: Microsoft.AspNetCore.All 2.0.0-preview1-final
- Environment (Operating system, version and so on): Windows 10 x64, Visual Studio Code
- .NET Framework version: .Net Core 2.0
- Additional information:
```

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

ImageSharp.ImageProcessingException: An error occured when processing the image using ResizeProcessor`1. See the inner exception for more detail. ---> System.TypeLoadException: Could not create array type 'ImageSharp.Processing.Processors.ResamplingWeightedProcessor`1+WeightsWindow[ImageSharp.Rgba32][]' from assembly 'ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ImageSharp.Processing.Processors.ResamplingWeightedProcessor`1.PrecomputeWeights(Int32 destinationSize, Int32 sourceSize)
   at ImageSharp.Processing.Processors.ResamplingWeightedProcessor`1.BeforeApply(ImageBase`1 source, Rectangle sourceRectangle)
   at ImageSharp.Processing.ImageProcessor`1.Apply(ImageBase`1 source, Rectangle sourceRectangle)
   --- End of inner exception stack trace ---
   at ImageSharp.Processing.ImageProcessor`1.Apply(ImageBase`1 source, Rectangle sourceRectangle)
   at ImageSharp.Image`1.ApplyProcessor(IImageProcessor`1 processor, Rectangle rectangle)
   at ImageSharp.ImageExtensions.Resize[TPixel](Image`1 source, Int32 width, Int32 height, IResampler sampler, Rectangle sourceRectangle, Rectangle targetRectangle, Boolean compand)
   at ImageSharp.ImageExtensions.Resize[TPixel](Image`1 source, Int32 width, Int32 height, IResampler sampler, Boolean compand)
   at ImageSharp.ImageExtensions.Resize[TPixel](Image`1 source, Int32 width, Int32 height)
   at MyFancy.Components.Manager.Resize(....) in ...
```

**Comment by JimBobSquarePants** [comment]
This is the kind of thing I wish we had the .NET team helping us out with. Not a clue what is going on unless there is something missing due to the AspNetCore preview shift to `netcoreapp2.0`?

**Comment by BravoTango86** [comment]
Last known working version for me is ImageSharp 1.0.0-alpha9-00034 with ImageSharp.Drawing 1.0.0-alpha9-00084.

Reference to System.Runtime.ComplilerServices.Unsafe is 4.4.0-preview1-25219-02 in ImageSharp 1.0.0-alpha9-00034 and 4.4.0-preview1-25305-02 in ImageSharp 1.0.0-alpha9-00089.

**Comment by BravoTango86** [comment]
Yep 34 works fine with 2.0.0-preview1-005977.

**Comment by JimBobSquarePants** [comment]
I think this is outwith our power to sort for now then I'm afraid. 😞  

We can only wait until the dust has settled and the Microsoft libraries are out of preview.

**Comment by BravoTango86** [comment]
It seems that it's having problem with arrays of WeightsWindow.  Using NearestNeighborResampler bypasses all the grief and seems to work.

**Comment by JimBobSquarePants** [comment]
Yeah, that's what the stacktrace above says. 

@antonfirsov What are your thoughts on this? Seems like a dependency issue in the MS libraries but I'm wondering whether there is something funky going on. i.e. a change in the underlying libraries.

**Comment by antonfirsov** [comment]
Well I have no .NET Core 2.0 installed, but I think I got it! We have a `Span<T>` on the heap by instantiating `WeightsWindow[]`! Looks like I violated the rule I keep bullying people with ^^

It works with .NET core 1.1 because it lacks the runtime-provided native span.

The quickest workaround that comes into my mind:
Let's pin `WeightsBuffer.dataBuffer` (Making use of `Buffer2D<T>.Pin()`), and let's turn `WeightsWindow.Span` into a pointer again. This should not affect performance.

**Comment by JimBobSquarePants** [comment]
@antonfirsov I didn't spot that! Well done! 

Yeah, that fix is fine by me. You wanna do it?

**Comment by JimBobSquarePants** [comment]
@dbeuchler @BravoTango86 Once the CI has finished building we should have it working properly now. Please test and let us know.

**Comment by dbeuchler** [comment]
Tested it on OSX 10.12 right now and it works. Will check it on windows later.
Thank you for the changes and help!
