### ISSUE TITLE
Converting resized Image<Rgba32> to a stream

### ISSUE THREAD

**Issue by bdbrown4** [JimBobSquarePants/ImageSharp#226]
I am at a loss of where to go... any suggestions? I need to convert the new object back into a stream.

**Comment by antonfirsov** [comment]
What kind of stream do you need? One with a specific format? Or just raw pixel data? Also: Please use our gitter channel for questions!

**Comment by bdbrown4** [comment]
Sorry for not using the chat! Just a memory stream, but I have figured it out! I wasn't initializing the stream before saving to it! For future cases, I will use gitter! Thanks!
