### ISSUE TITLE
Full Framework Support

### ISSUE THREAD

**Issue by willdean** [JimBobSquarePants/ImageSharp#228]
It's not 100% clear to me that it's the intention of the ImageSharp to have first-class netfx (full framework) support - this would be really useful to us to try and migrate to IS before Core rather than at the same time.

Although I was told elsewhere that the readme makes this clear, as far as I can see it only mentions Net Standard 1.3+, which does require one to go and look up what the implications of that are.  (It does imply .NET 4.5 support, I think)

However, the reality of doing a nuget install into a 4.6 project is that *dozens and dozens* of files are download into packages, and swathes of references (27 into one project) and binding redirects are added, including for things which I perceive to have nothing to do with a graphics library.  Unfortunately, one of these is `System.Net.Http`, which then foists [this](https://github.com/dotnet/corefx/issues/11100) running sore onto our project, causing it to fail to serve any pages. 

So, as of today, the upshot of adding ImageSharp to a .NET 4.6 ASP.NET project is to break it completely, for reasons which are nothing to do with IS or graphics.

Clearly the craptitude of nuget is not something that ImageSharp is responsible for, and nor can it fix it, but would it be the case that if ImageSharp explicitly targeted the full framework in addition to the NET standard targets that this might improve?   Would that be possible?

**Comment by willdean** [comment]
Actually, I'm going to close this because I think I'm wasting your time here...

**Comment by mellinoe** [comment]
We'd be happy to discuss the System.Net.Http issue over in that corefx issue, if you'd like (and to avoid polluting the discussion here). My initial impression is that you need to just update your project to reference version "4.3.1" of System.Net.Http, which includes our recent fixes for the issues you're seeing (hopefully 😄 ).

**Comment by willdean** [comment]
@mellinoe Thanks for this - I was aware that there was now a fix and hopefully the ImageSharp guys will include it if it is actually them calling-up the dependency directly.  I do follow that particular issue in the same spirit as one watches hockey for the fights or motor sport for the crashes.

The bigger issue for me is whether I want a library that I need to scan-convert a few lines into a bitmap to inject a chain of dependencies into a project of such enormous complexity that they can introduce a show-stopping bug that takes 6+ months to get fixed.  It just feels like a bad risk to our business.  Every Nuget-injected library / binding redirect is a ticking time-bomb, with some of them primed to explode only at run-time, after deployment.   I don't want any more of them...
