### ISSUE TITLE
.Net 4.5 DLL in Nuget

### ISSUE THREAD

**Issue by Saftpresse99** [JimBobSquarePants/ImageSharp#231]
Hi,

i want to know if it's possible to add a assembly for .net 4.5 or higher into the nuget package?
Thank you!

**Comment by NightOwl888** [comment]
According to the README:

> Built against .Net Standard 1.1 ImageSharp can be used in device, cloud, and embedded/IoT scenarios.

.NET Standard 1.1 natively supports .NET Framework 4.5 and higher according to the [.NET Standard Platform Support Chart](https://docs.microsoft.com/en-us/dotnet/standard/library#net-platforms-support).

Since .NET Standard 1.1 *does* natively support .NET Framework 4.5, is there some other reason you need it to be compiled specifically against .NET Framework 4.5?

**Comment by JimBobSquarePants** [comment]
Hey @Saftpresse99 Our [Gitter](https://gitter.im/ImageSharp/General?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel is the best place to ask questions. I'm gonna close this issue so please ask there if you need anything else. Cheers!

@NightOwl888 Thanks for answering the question 👍

**Comment by Tilation** [comment]
@JimBobSquarePants The glitter channel doesn't exist anymore, could you post the answer here so future users don't have to jump from platform to platform searching for your communication channels?

**Comment by JimBobSquarePants** [comment]
The answer is above.

https://github.com/SixLabors/ImageSharp/issues/231#issuecomment-304711339

**Comment by Tilation** [comment]
@JimBobSquarePants I'm sorry, I can't find anywhere a .NET Standard 1.1 version of the package, only .NET Standard 1.3 which is not net450 compatible

**Comment by JimBobSquarePants** [comment]
Microsoft [don't support .NET 4.5 anymore](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework) so we don't either. 

You really, really should not be using it in any production environment. Microsoft [no longer provide updates including security fixes or technical support](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/#closing) for versions less than .NET 4.6.2

ImageSharp V1 supports .NET Standard 1.3
ImageSharp V2 supports .NET Standard 2.0

**Comment by Tilation** [comment]
Understandable, thanks!
