### ISSUE TITLE
How to know whether a jpg is progressive?

### ISSUE THREAD

**Issue by OscarCanek** [JimBobSquarePants/ImageSharp#235]
Using the example to load an image 
```
string path = @"images\image.jpg";
using (Image<Rgba32> image = Image.Load(path))
{
...
}
```

How can I know whether the image is progressive?
How can I convert a baseline jpg to progressive jpg?

**Comment by JimBobSquarePants** [comment]
Hi Oscar,

We don't support progressive encoding yet. We're hoping someone in the community will step up and help us. It's hard! 

Cheers

James

P.s. We have a gitter channel for questions. The issue tracker us for well.... Issues.
