### ISSUE TITLE
Lines drawn to negative coordinates will have missing parts based on angle

### ISSUE THREAD

**Issue by Symbiatch** [JimBobSquarePants/ImageSharp#237]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When drawing lines that cross either Y or X axis to negative side the lines will have pieces missing of them. The missing parts depend on the angle of the line.

### Steps to Reproduce
```
using ImageSharp;
using ImageSharp.Drawing.Pens;
using ImageSharp.PixelFormats;
using System.IO;
using System.Numerics;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			var image = new Image<Argb32>(256, 256);
			var pen = new Pen<Argb32>(new Argb32(255, 255, 255), 5f);

			for (int i = 0; i < 300; i += 20)
			{
				image.DrawLines(pen, new Vector2[] { new Vector2(100, 2), new Vector2(-10, i) });
			}

			image.SaveAsPng(File.OpenWrite("isharp.png"));
		}
	}
}

```

This should draw solid lines past the left border and the topmost line should go properly almost horizontal. Instead, the topmost line is missing most of it, the other lines have big parts missing near the edge.

This does not happen when going past the bottom or right edges.

![isharp](https://cloud.githubusercontent.com/assets/2326085/26678652/2fa9c174-46da-11e7-8ffc-2b2a3e068935.png)

### System Configuration

- ImageSharp 1.0.0-alpha9-00105
- ImageSharp.Drawing 1.0.0-alpha9-00100
- Windows 10 Pro 1703 (15063.296)
- .NET Framework 4.6.2

**Comment by JimBobSquarePants** [comment]
@Symbiatch Thanks for raising such a clear issue! We really appreciate that 👍

**Comment by tocsoft** [comment]
Thanks for reporting this, I've now pushed a fix up. Once the CI server does its magic it'll be available.

__For general information__

This bug was only introduced for the `image.Draw()` family of apis when my last PR landed however the issue was affecting general `image.Fill()` ones for a while. _obviously no one must have tried to draw shapes something partially off canvas._
