### ISSUE TITLE
ImageSharp.ImageFormatException : Unknown marker when resizing image

### ISSUE THREAD

**Issue by mmort75** [JimBobSquarePants/ImageSharp#238]
I get this error "Message: ImageSharp.ImageFormatException : Unknown marker" when running following code 

`Stream imageStream = File.OpenRead("C:\\temp\\biggerimage.jpg");
using (var image = Image.Load(imageStream))
                {
                    image.Resize(1920, 1024)
                        .Save(outputStream);
                }`

- ImageSharp version: 1.0.0-alpha9-00105
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: dotnet core 1.1

**Comment by tocsoft** [comment]
Unknow marker is referring to an issue in the image itself.

Does it happen on all images or just the one? Have you confirmed the image loads with other software?

Please provide the image that's broken for us to be able reproduce your issue.

**Comment by mmort75** [comment]
Thanks I have attached image
![biggerimage](https://cloud.githubusercontent.com/assets/4156816/26680376/92d8758c-471c-11e7-81d8-62ec301b092a.jpg)

**Comment by mmort75** [comment]
I have only had this problem with Images taken on the Surface Pro tablet which has higher resolution images than the one's I've been testing with before from other WebCams

**Comment by tocsoft** [comment]
awesome thanks for that 👍 that was exactly what I needed to put together a fix.

**Comment by JimBobSquarePants** [comment]
We've got a fix. Thanks @tocsoft and I'll merge it in a mo. 

For the curious whatever is taking the picture is adding data I don't recognize to the `App2` marker It's header starts with `IntelMknote\0MK` which I couldn't find any info on.
