### ISSUE TITLE
Needed Encoding and Decoding features in Image Filter

### ISSUE THREAD

**Issue by sabariAnand** [JimBobSquarePants/ImageSharp#239]
Hi All,

Is encoding and decoding feature available in the ImageSharp for the Image filters? Where can I find the documentation for using such functions, if it is available. If it is not available, can I please know when can I get the feature?

Regards,
Sabari Anand

**Comment by JimBobSquarePants** [comment]
Hi Sabari,

Thank you for your interest in the library. 

Unfortunately I have absolutely no idea what you mean. Could you please use the Gitter channel that we link to in the readme and contribution guidlines for questions and we can try to figure out what you are asking for. 

Cheers

James
