### ISSUE TITLE
Png's are encoding wrong after 1.0.0-alpha-000047

### ISSUE THREAD

**Issue by KLuuKer** [JimBobSquarePants/ImageSharp#24]
png's are encoded incorrectly on version v1.0.0-alpha-000053 and higher (including 57)

last know good version is v1.0.0-alpha-000052
so i think something went wrong in this commit https://github.com/JimBobSquarePants/ImageSharp/commit/f814dc3609c53d33ba42ac0bdf24f6b799f8420a

k so after version v1.0.0-alpha-000053 the error's get really obvious (weird colored blocks)
but before that some images are still encoded incorrectly (getting chopped off) and smaller resize actions turning into black images

currently checking how far back this starts occuring

**Comment by KLuuKer** [comment]
the actual last known good version is 1.0.0-alpha-000047
so the real problem starts on version v1.0.0-alpha-000048
which would be this commit https://github.com/JimBobSquarePants/ImageSharp/commit/52cddd328e2dde5536f46e5553bd280c4564e83a

i have a large batch of images and on version 48 and up some of them are not getting processed all the way
for example it would stop encoding part way trough the image
and images i make into small thumbnails end up getting completely black

**Comment by JimBobSquarePants** [comment]
@KLuuKer  Thanks for all the extra info that was really useful! Turns out I'd moved a line inside the using statement for the deflater stream. 1.0.0-alpha-000062 work fine now for me.

https://github.com/JimBobSquarePants/ImageSharp/commit/52cddd328e2dde5536f46e5553bd280c4564e83a#diff-c61aac0b8f9e954e0dae0ff548a8b063R603

**Comment by KLuuKer** [comment]
bad news everyone....  :(

seems it's not completely fixed (although its allot better now)

there is a small amount of images that have the same "it just stop encoding parts" or weird block parts or other encodings issues

i only get some issues for some resolutions tough, so maybe it's not the pngencoder but some other resizing stuff

i will check\try some more stuff later, but i have todo some other stuff first

``` C#
using (var thisIsMyOutputData = new MemoryStream())
{
    // yes its a normal memorystream and something weird
    ImageResizer.Resize(img.Blob, thisIsMyOutputData, true, 300, 300)
}
```

``` C#
internal static void Resize(byte[] image, Stream outputStream, bool resize, int newWidth, int newHeight)
        {
            using (var stream = new MemoryStream(image, false))
            {
                Image<Color, uint> img = new Image(stream);
                {
                    if (resize && (img.Width > newWidth || img.Height > newHeight))
                    {
                        if (img.Width > img.Height)
                        {
                            newHeight = (int)(img.Height / (img.Width / (double)newWidth));
                        }
                        else
                        {
                            newWidth = (int)(img.Width / (img.Height / (double)newHeight));
                        }

                        img = img.Resize(newWidth, newHeight, new Lanczos3Resampler(), true);
                    }

                    if (img.ExifProfile != null)
                    {
                        var invalidValues = img.ExifProfile.InvalidTags.ToList();
                        foreach (var tag in invalidValues)
                        {
                            img.ExifProfile.RemoveValue(tag);
                        }

                        var values = img.ExifProfile.Values.ToList();
                        foreach (var tag in values)
                        {
                            img.ExifProfile.RemoveValue(tag.Tag);
                        }
                    }

                    if (img.Properties != null && img.Properties.Count > 0)
                    {
                        img.Properties.Clear();
                    }

                    var encoder = new PngEncoder()
                    {
                        Quality = int.MaxValue,
                        CompressionLevel = 9,
                    };

                    encoder.Encode(img, outputStream);
                }
            }
        }
```

**Comment by dlemstra** [comment]
@KLuuKer Making a small sidestep here... Why are you not setting the ExifProfile to null to remove the profile? I do think I still need to add a `RemoveInvalidTags()` and a `Clear()` method to the class.

**Comment by KLuuKer** [comment]
@dlemstra wouldn't it be better if it didn't get loaded in the first place? :)
Didn't change anything tough, still have the same issue.

**Comment by KLuuKer** [comment]
the perpetrator in question (this is a jpeg, yes i know i shouldn't turn it into a png but it should still get converted correctly)

![resize-me](https://cloud.githubusercontent.com/assets/12729178/20262839/54baab62-aa64-11e6-88a2-5651dcf1eba2.jpg)

even when skipping the resize it is not correct
![skip-resize](https://cloud.githubusercontent.com/assets/12729178/20262926/b78fb8a4-aa64-11e6-8402-593c9e151b95.png)

some other sizes
![medium](https://cloud.githubusercontent.com/assets/12729178/20262945/d03085b4-aa64-11e6-96d3-069042236af6.png)
![thumb](https://cloud.githubusercontent.com/assets/12729178/20262951/d3fa0832-aa64-11e6-9faa-6204b6c4048a.png)

**Comment by KLuuKer** [comment]
hmmmm, i think all of the images that are encoded incorrectly are jpeg files

**Comment by JimBobSquarePants** [comment]
Odd @KLuuKer... I'm not seeing this in my tests.

Here's the image encoded as a png
![butterfly](https://cloud.githubusercontent.com/assets/385879/20264022/95cd6f8c-aabd-11e6-99c9-1a39d70950ff.png)

And here is it resized as a png using the Lancsoz3 sampler
![butterfly-lanczos3](https://cloud.githubusercontent.com/assets/385879/20264087/e2150008-aabd-11e6-8f89-2fbf63e30af4.png)

BTW that whole code could be written in a much more concise manner...

``` c#
// Resizing with one dimensions will automatically preserve the aspect ratio.
// Png doesn't preserve EXIF data so you don't need to remove it.
new Image(stream)
.Resize(newWidth, 0, new Lanczos3Resampler(), true)
.SaveAsPng(output);
```

@dlemstra Could you also dl the image and test on your machine? I want to make sure there is nothing odd going on.

**Comment by KLuuKer** [comment]
@JimBobSquarePants even when using your code, i get errors

``` C#
  internal static void Resize(byte[] image, Stream outputStream, bool resize, int newWidth, int newHeight)
        {
            using (var stream = new MemoryStream(image, false))
            {
                new Image(stream)
                    .Resize(newWidth, 0, new Lanczos3Resampler(), true)
                    .SaveAsPng(outputStream);
            }
        }
```

i must admit I'm running this with multiple images simultaneous about 80 different webrequest (our product index page), so this could be a concurrency issue

**Comment by KLuuKer** [comment]
i made sure all image's are the same, and they have all different kinds of encoding issues
``` C#
image = File.ReadAllBytes("d:\\temp\\resize-me.jpg");
```
this is what i get when i have muliple encodings running, some are incorrect in different ways, some incorrect in the same way, some are just fine
![sample-output](https://cloud.githubusercontent.com/assets/12729178/20264988/a4b63e6a-aa6e-11e6-9a3e-5500a6019fde.png)

**Comment by JimBobSquarePants** [comment]
Ah... now that is interesting. Everything here _should_ be threadsafe but maybe it isn't.

And it's definitely fine before the commit at the top of the thread? And only happens when encoding png files?

If so, The only real change I have made to the png encoder is using is an `ArrayPool<T>` to reduce allocation but that is supposed to be threadsafe also.

**Comment by KLuuKer** [comment]
we can ignore the resize code, i commented that out and its still wrong, gonna try outputting jpegs

**Comment by JimBobSquarePants** [comment]
Ok... Can you do me a huge favour please and also test gif and bitmap. I want to narrow it down to the png encoder.

**Comment by KLuuKer** [comment]
version 47 png output is definitely fine

version 64 bmp output is fine (but damn they are huge :)
version 64 gifs have such great pallet support
![looks-gif-to-me](https://cloud.githubusercontent.com/assets/12729178/20265562/0aabb4fe-aa72-11e6-9702-721bfd0f8b69.gif)

**Comment by JimBobSquarePants** [comment]
Thanks for all that... Yeah bmps are uncompressed, they'll be massive. 

The encoder it is then. I'll knock up a parallel test and keep at it.

**Comment by KLuuKer** [comment]
my simple console app i made just now (same issue)

``` C#
Parallel.For(1, 50, (i) =>
            {
                var image = File.ReadAllBytes("resize-me.jpg");
                using (var outputStream = new FileStream("output\\" + i + ".png", FileMode.Create))
                {
                    using (var stream = new MemoryStream(image, false))
                    {
                        new Image(stream)
                            .SaveAsPng(outputStream);
                    }
                }
            });
```

**Comment by KLuuKer** [comment]
so i tested 47-51 with the code above and they are fine
but on verion 52 (commit https://github.com/JimBobSquarePants/ImageSharp/commit/bdb53d88ca7cec94943ea2d7a5908a89ef87d0bd) i get this (the top is wrong for all but the last image in the for loop)
![version-52](https://cloud.githubusercontent.com/assets/12729178/20266065/9e935cc4-aa74-11e6-9d76-b82b624da780.png)

**Comment by JimBobSquarePants** [comment]
Give that push a go please. I was able to recreate the issue with a test and fix it. Bonus was a 20% memory usage reduction.

**Comment by KLuuKer** [comment]
had to wait for the package to get pushed :)
so with the butterfly image in the 50 parallel console app test it works fine,
but when i run the entire product page against it i still get some encoding errors

are you aware of ArrayPool.Shared documentation?
> It maintains arrays of multiple sizes, and **may hand back a larger array than was actually requested**, but will never hand back a smaller array than was requested.

**Comment by JimBobSquarePants** [comment]
Sorry, didn't mean to close that. 

Yeah, I've read that, if you look I'm only ever reading the `bytesPerScanline` value length from each buffer. I was just doing some debugging in parallel experimenting with something else though and sometimes that value wasn't correct. 

I can't for the life of me see how that would happen though, all the variables are private instance ones.  

It's after 1am here so I won't be able to do anything more tonight I'm afraid. I'll have another look when I'm more fresh.

**Comment by KLuuKer** [comment]
Go take your well deserved sleep, you have a great project I'm leeching off.
I just wont update production :)

**Comment by JimBobSquarePants** [comment]
Once more unto the breach, dear friends, once more...

**Comment by KLuuKer** [comment]
Seems to work fine for me :shipit:

o wait you already did 😄
