### ISSUE TITLE
Make MathF, Constants, and ComparableExtensions public

### ISSUE THREAD

**Issue by Inumedia** [JimBobSquarePants/ImageSharp#246]
### Description
MathF, Constants, and ComparableExtensions should be made public so as to easily add other PixelFormats.

- ImageSharp version: 1.0.0-alpha9-00139
- Environment (Operating system, version and so on): All

**Comment by antonfirsov** [comment]
@Inumedia we want to keep our public API as narrow as possible keeping our ability to change these internal utilities as our design evolves, so I don't the API-s you're mentioning should be public. 

A possible change for MathF: A standard `MathF` class with it's functionality [is coming](https://github.com/dotnet/corefx/issues/1151), we should adapt it in the future.

These utilities are really thin, so you can easily include them into your project. If you are implementing a new pixel type you might also PR it into ImageSharp ;)

**Comment by JimBobSquarePants** [comment]
Our `MathF` class only actually exists due to the linked CoreFX issue. I wanted to be prepared to switch out easily when it's available. 

Clamp is also []([coming](https://github.com/dotnet/corefx/pull/12311)) via `System.Math` so we don't want to expose our extensions yet either.
