### ISSUE TITLE
Gif quality after resize is bad, the image quality setting doesn't affect properly

### ISSUE THREAD

**Issue by mhamri** [JimBobSquarePants/ImageSharp#259]
I am trying to save some gif with less size, with some tools like [this one ](https://ezgif.com/optimize/ezgif-2-3a6e9efa3d.gif ) i can decrease the size of the image up to 50% when still the picture is acceptable 

but when i try to do the same with image sharp with following code 

```C#
private Size ResizeFit(Size originalSize, Size maxSize)
{
    var widthRatio = (double)maxSize.Width / (double)originalSize.Width;
    var heightRatio = (double)maxSize.Height / (double)originalSize.Height;
    var minAspectRatio = Math.Min(widthRatio, heightRatio);
    if (minAspectRatio > 1)
        return originalSize;
    return new Size((int)(originalSize.Width * minAspectRatio), (int)(originalSize.Height * minAspectRatio));
}

public Task<SavingCacheResult> SaveToCacheAsync(string fileId, Stream file)
{
    var result = new SavingCacheResult();
    try
    {
        var animatedFileName = GetCachedFilePath(fileId, CachedFileType.Animated);

        using (Image<Rgba32> img = Image.Load(file))
        {
            var originalSize = new Size(img.Width, img.Height);
            var newSize = ResizeFit(originalSize, _maxSize);
            result.Width = newSize.Width;
            result.Height = newSize.Height;
            
            img.Resize(newSize.Width, newSize.Height)
                .Save(animatedFileName, new GifEncoderOptions() { IgnoreMetadata = true, Quality = _gifQuality });
        }
        
        result.Successful = true;
    }
    catch (Exception e)
    {
        _logger.LogDebug("error saving cached version", e);
        result.Successful = false;
    }

    return Task.FromResult(result);
}
```
the original : (in case can't see the image it's [here](https://media.giphy.com/media/3o7bufOhrt1GkWwnmM/giphy.gif) )

the image output become really bad. this image saved with quality 150. i tried even with 256 and quality was almost the same, if i set the image quality as 1. i can't even open the image. windows image viewer show that it can't open the image. (in case can't see the image it's [here](http://20gif.com/image/Animated/34436604-c64d-40a1-92da-de7b8eea43a5_Default.gif?refr=Self))

so i wonder if my code is wrong or i'm setting something wrong

**Comment by JimBobSquarePants** [comment]
Hi @mhamri 

Please don't delete the issue template. It's there for very good reason.

Your original image is not a gif so of course there will be quality loss. Dithering is also turned off by default with animated gifs to prevent pixel dancing.

**Comment by mhamri** [comment]
Hi @JimBobSquarePants 
I updated the question, sorry to delete the template. how do I turn on Dithering? any sample code? 

Thanks

**Comment by tocsoft** [comment]
At the moment there is no way to enable dithering on animated gif (just double checked in the source) 

I've added #262 to tack the feature.

re:quality setting. That is a badly named setting for gif, what it actaully relates to is the palette size (which it'll soon be renamed to as part of encoder/decoder refactoring effort currently underway).

**Comment by mhamri** [comment]
@tocsoft Thanks!
