### ISSUE TITLE
Feedback after text wrapping

### ISSUE THREAD

**Issue by lasharela** [JimBobSquarePants/ImageSharp#263]
Hi,
We have dynamic text with fixed with. It's is important to know text was wrapped or not.

I have a few questions:

1. May I have some status - was text wrapped or not
2.  How many lines I have after wrapping
3. What is the height (in pixel) to the wrapped text at all (I want to align it vertically)

Here is image, which I'm trying to render and now I'm talking about green text (person's name)

![lasha s version - 1](https://user-images.githubusercontent.com/2189316/27641502-173179bc-5c2d-11e7-8d26-d4b89dfd440b.png)

**Comment by tocsoft** [comment]
For simple vertical alignment just specify  `textOptions.VerticalAlignment = VerticalAlignment.Center` on the `TextGraphicsOptions` you passed into `image.DrawText(..)` it will vertically align for you. For what your trying to do (i.e. place text after a vertically aligned block of text) you will want to use use `TextMeasure.Measure(text, new RendererOptions(font, 72))` (ImageSharp renders text at 72 dpi for font size calculations by default) to find out the the expected text size and use that to determine how to position things. 

The option for feed back as part of rending will not be added, but you have better alternatives available to reproduce the effect your after.
