### ISSUE TITLE
Add additional IPackedPixel<TColor, TPacked>  implementations.

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#27]
We need to add implementations for the following [MonoGame](https://github.com/MonoGame/MonoGame/tree/4f15a517c9a7edd45249c1b44f3c753f51660a75/MonoGame.Framework/Graphics/PackedVector) classes and tests to match.

- [x] Alpha8 
- [x] Bgr565 
- [x] Bgra444 
- [x] Bgra565 
- [x] Byte4 
- [x] HalfSingle 
- [x] HalfVector2 
- [x] HalfVector4 
- [x] NormalizedByte2 
- [x] NormalizedByte4 
- [x] NormalizedShort2 
- [x] NormalizedShort4 
- [x] Rg32 
- [x] Rgba1010102 
- [x] Rgba64 
- [x] Short2 
- [x] Short4

**Comment by JimBobSquarePants** [comment]
We can now do some pretty crazy things.

```
var image = new Image(inputStream)
    .To<Bgr565, ushort>()
    .To<Bgra4444, ushort>()
    .To<Bgra5551, ushort>()
    .To<Byte4, uint>()
    .To<HalfSingle, ushort>()
    .To<HalfVector2, uint>()
    .To<HalfVector4, ulong>()
    .To<Rg32, uint>()
    .To<Rgba1010102, uint>()
    .To<NormalizedByte2, ushort>()
    .To<NormalizedByte4, uint>()
    .To<NormalizedShort2, uint>()
    .To<NormalizedShort4, ulong>()
    .To<Short2, uint>()
    .To<Short4, ulong>()
    .Save(outputStream);
```

WHAAAAAAAAAAAAT???!!!!!

**Comment by davepermen** [comment]
i wanna see a pic before/after :) poor image has surely gone through hell

**Comment by JimBobSquarePants** [comment]
😄 It's actually in good shape what with the scaling and offset adjustments. It's red simply because `HalfSingle` only preserves the red channel. I deliberately left out `Alpha8` since it would preserve nothing in a jpeg.

![calliphora before](https://cloud.githubusercontent.com/assets/385879/20810428/d9f5de8a-b85d-11e6-90ba-95088ae643f9.jpg)

![calliphora after](https://cloud.githubusercontent.com/assets/385879/20812395/7f3acf5c-b865-11e6-8cbe-bf497046952a.jpg)
