### ISSUE TITLE
Could not load file or assembly System.ValueTuple

### ISSUE THREAD

**Issue by xalikoutis** [JimBobSquarePants/ImageSharp#270]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
an error is thrown when the following is called. image is a byte[] and i have installed System.ValueTuple 4.3.1 which imagesharp depends
`var input = Image.Load(image)`
Error
```
Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified., Stack=   at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at ImageSharp.Image.Load[TPixel](Configuration config, Byte[] data)
```

### Steps to Reproduce
`var input = Image.Load(image)`

### System Configuration
windows 10 and also in prod linux docker

- ImageSharp version: 1.0.0-alpha9-00170
- Other ImageSharp packages and versions:NA
- Environment (Operating system, version and so on):windows,linux
- .NET Framework version: .net core 1.1
- Additional information:

**Comment by xalikoutis** [comment]
update System.ValueTuple to 4.4.0-preview1-25305-02 and everything works fine

**Comment by OskarKlintrot** [comment]
Isn't there any other way to solve this than have to use the same version that ImageSharp uses? I don't really want to have to look at ImageSharp source code when updating and make sure I use the same version. This is also forcing me to use a preview version of something I don't want a preview version of.

**Comment by JimBobSquarePants** [comment]
Ummmmmm.... ImageSharp is an alpha?! We are using those versions because we need them to build a performant and usable library. 

Those previews will cease to be once Netcore 2 is released so I really wouldn't worry.

**Comment by OskarKlintrot** [comment]
I know but ImageSharp is forcing me to use other libraries preview versions and I don't want that. And I definitely don't want to look in ImageSharp source code to figure out what is breaking things. I will move to Netcore 2 once it's released so then I don't mind.

**Comment by antonfirsov** [comment]
@OskarKlintrot At the time ImageSharp get's RC, these libraries will be in an RC state as well. We are building a future-proof API with the newest netstandard/netcore toys, so this is a reasonable tradeoff. "Being in preview" is a transitive relation, so I don't see any problem with using preview packages in a preview library.

I can only qute the disclaimer from our README.md:
> ImageSharp has made excellent progress and contains many great features but is still considered by us to be in early stages (alpha). As such, we cannot support its use on production environments until the library reaches release candidate status.

**Comment by OskarKlintrot** [comment]
@JimBobSquarePants already noted it and I'm fine with that! I love new toys!
