### ISSUE TITLE
Async Support is missing

### ISSUE THREAD

**Issue by TsengSR** [JimBobSquarePants/ImageSharp#272]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've skipped through the source and can't seem to find a single real async method, not even for the most basic methods which read images from file system like `Image.Load(...)`. None of them is awaitable. 

It makes the library kind of useless for anything related to ASP.NET Core since I/O operations (reading from network connection, file system or remote azure storage) will block the request thread, killing any scale-ability of the web application.

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00170
- Environment (Operating system, version and so on): Windows for development, Linux for deployment
- .NET Framework version: .NET Core 1.1
- Additional information:

**Comment by JimBobSquarePants** [comment]
Use Gitter please

**Comment by antonfirsov** [comment]
Yeah gitter is our forum for initial feature discussions.

A short answer though:
You can workaround this by reading your network/file stream into `MemoryStream` asynchronously, then pass it to `Image.Load()`. Our initial implementation would be the same, implementing fine-grain async stream processing in codecs is not a key priority for at the moment. It's extremely hard for a format like jpeg, we need to make our  jpeg decoder faster & more memory friendly first.
