### ISSUE TITLE
Png's are decoding wrong after 1.0.0-alpha-000061

### ISSUE THREAD

**Issue by KLuuKer** [JimBobSquarePants/ImageSharp#28]
png's are decoded incorrectly on version v1.0.0-alpha-000062 and higher (including 95)

last know good version is v1.0.0-alpha-000061
so i think something went wrong in this commit https://github.com/JimBobSquarePants/ImageSharp/commit/27522da82b93d19c530e848b55ef8e9ad4e46d1c

i think it's the same as #24 but this time it's in the **de**coder, i only have 1 specific image that gives me the issue. all of my other images decode&encode just fine (on version 95)

tested with output format: png,jpeg,bmp,gif (all give the same issue)
used the same simple console app as in https://github.com/JimBobSquarePants/ImageSharp/issues/24#issuecomment-260329863

please don't forget to sleep this time 😄 

original source file:
![source-file](https://cloud.githubusercontent.com/assets/12729178/20752580/45f422e8-b702-11e6-8848-9ae9080537dc.png)

single-thread output:
![single-thread](https://cloud.githubusercontent.com/assets/12729178/20752593/5176a3de-b702-11e6-8a4c-2c589e269c28.png)

multi-thread output:
![bad-file](https://cloud.githubusercontent.com/assets/12729178/20752600/5a8a371a-b702-11e6-8fdd-60c513a79a44.png)

**Comment by KLuuKer** [comment]
it could also be a issue with the png itself, because if i resave the image with irfanview it multithread decodes & encodes correctly

**Comment by JimBobSquarePants** [comment]
Hmmmm... Probably the ArrayPool stuff again. Odd, it really doesn't seem to be threadsafe. 

Would you be able to fork the repo and conduct your tests with a reverted decoder? I'll test myself when I can.

**Comment by KLuuKer** [comment]
Well i checked and the ArrayPool is definitely thread safe

**BUT** you will eventually get **MORE** bytes than you asked for. (the docs say it will return a array of MINIMAL the specified length). so great care must be taken in using the bytes that are returned by the pool

https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L338
i replaced those pool rent's with ```new byte[this.bytesPerScanline];```
and that worked, so the issue would probably be in the processing of 
https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L365
as that doesn't have the correct length passed to it

sorry if it sounds like i'm ranting like you don't know what you are doing

**Comment by JimBobSquarePants** [comment]
Och not at all, at least it looks like it should be an easy fix then. Would you like to give it a go? You have the advantage of tests that work. 

I really need to beef up my parallel test.
