### ISSUE TITLE
Blending & Padding. How to Position a smaller image on a larger canvas using an x,y offset.

### ISSUE THREAD

**Issue by gk7gk7** [JimBobSquarePants/ImageSharp#32]
I have a background image of lets say `1000 x 600` pixels and a smaller overlay image of `128 x 80` pixels.

__the desired outcome__
What I need to do is produce an output image by placing the ovelay.jpg on the background.jpg at the x,y coordinates.

__what I've tried so far__
The following takes the overlay to the middle of the larger background image. I cannot seem to find how to affect the positioning using the x,y offsets. 

```csharp
    using (var backgroundStream = StreamExtentions.GetImageStream("scene_bg.jpg")) {
        var outPath = @"c:\temp\output.jpg";
        using (var output = File.OpenWrite(outPath)) {
            var background = new Image(backgroundStream);
            var overlay = default(Image);
            using (var overlayStream = StreamExtentions.GetImageStream("overlay.png")) {
                overlay = new Image(overlayStream);
            }

            var opacity = 100;
            var x = 0;
            var y = 0;
           
            var result = overlay.Pad(background.Width, background.Height);
            background .Blend(result, opacity)
                                .SaveAsJpeg(output);
        }
    }
```

Is this possible at the moment?

**Comment by JimBobSquarePants** [comment]
Hi @gk7gk7 please see #14 

There are new options available on the latest build which allow both setting position and size. Please download that and give it a go.

Cheers

James

**Comment by gk7gk7** [comment]
Yes now i get the expected output.  
Thank you very much.

**Comment by JimBobSquarePants** [comment]
@cleftheris not to my knowledge could you be more specific please. It's impossible to determine what you mean.

**Comment by cleftheris** [comment]
@JimBobSquarePants :-) sorry about that I totally asked an out of context question, my bad. 

So in version `1.0.0-alpha-000122` I used the following code to achieve blending & positioning a smaller image on a larger background as stated above.

```csharp
    using (var backgroundStream = StreamExtentions.GetImageStream("scene_bg.jpg")) {
        var outPath = @"c:\temp\output.jpg";
        using (var output = File.OpenWrite(outPath)) {
            var background = new Image(backgroundStream);
            var overlay = default(Image);
            using (var overlayStream = StreamExtentions.GetImageStream("overlay.png")) {
                overlay = new Image(overlayStream);
            }

            var opacity = 100;
            var size = new Size(width:16, height:16);
            var location= new Point(x:120, y:60);
           
            background .Blend(image, 100, size, location)
                                .SaveAsJpeg(output);
        }
    }
``` 
after I update to the latest prerelease package `1.0.0-alpha4-00031` I don't know how to use this anymore since the `blend` overload I was using is missing.

```csharp 
background .Blend(image, 100, size, location)
```

Any help is appreciated.

**Comment by tocsoft** [comment]
the method got renamed to `DrawImage(...)`

**Comment by tocsoft** [comment]
but you will need to make sure your also referencing the `ImageSharp.Drawing` pacakge

**Comment by cleftheris** [comment]
@tocsoft  Thanks I will try it out!

**Comment by Scr34mik** [comment]
Hello, i cant seem to find .Blend() extension for "Image". I'm currently working with xamarin.mac project. Is there any replacement ?

**Comment by JimBobSquarePants** [comment]
@Scr34mik Don't ever spam our forums please.
