### ISSUE TITLE
Font Support

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#38]
The library will at some point need to add font support.

Libraries to consider basing the system on.

- https://github.com/MikePopoloski/SharpFont
- https://github.com/LayoutFarm/Typography

Ideally we shouldn't have any dependencies and absolutely no unmanaged dependencies as we need to deploy easily on web applications.

**Comment by tocsoft** [comment]
Just taken a very quick look over https://github.com/LayoutFarm/Typography and it looks like it would be quite easy to create an `IGlyphRasterizer` based on the `GDIGlyphRasterizer` implementation that should work with the new `ImageSharp.Drawing` code.

**Comment by prepare** [comment]
for your information,

I just create a branch named "only_WinGdiPlus".
(https://github.com/LayoutFarm/Typography/tree/only_WinGdiPlus).

I remove the dependency on PixelFarm rendering lib.

I think the code is easier for those who familiar with
System.Drawing.

**Comment by prepare** [comment]
some screenshots:
![s1](https://cloud.githubusercontent.com/assets/7447159/21261956/27e47a02-c3c1-11e6-9d33-377f1e97b621.png)
![s3](https://cloud.githubusercontent.com/assets/7447159/21261960/2c81ee46-c3c1-11e6-80c9-971198243ab3.png)

**Comment by tocsoft** [comment]
awesome... I'll try and give this a play over the weekend and see if I can't get something drawing.

**Comment by dlemstra** [comment]
I wonder if font support should be in a separate library that uses both the font and the Imagesharp library. What are your thoughts about this @JimBobSquarePants?

**Comment by tocsoft** [comment]
@dlemstra that's what I was thinking too. 

Something like an **ImageSharp.Drawing.Text** package. That would solve the small problem of [Typography](https://github.com/LayoutFarm/Typography) targeting _netstandard1.6_ and **ImageSharp** targeting  _netstandard1.1_

I even think everything in `ImageSharp.Drawing` should probably be in its own package too.

**Comment by dlemstra** [comment]
We have been talking about splitting stuff up and yes I think we should create an ImageSharp.Drawing library. You can find the other parts here: https://gitter.im/ImageSharp/General?at=584378420da034021b65da62. We already had ImageSharp.Drawing as a separate library.

**Comment by prepare** [comment]
@tocsoft :

> small problem of Typography targeting netstandard1.6 and ImageSharp targeting netstandard1.1

the Typography just need System.IO to find fonts and read a font file.
It can be use in .NET >= 2.0. 
I use shared code technique for different target platform, eg. NET20 , NETSTANDARD.
![s6](https://cloud.githubusercontent.com/assets/7447159/21278803/ca0c0284-c40f-11e6-9e59-82af301eea28.png)

**Comment by tocsoft** [comment]
✨ I've had some success with my text prototype which can be found at https://github.com/tocsoft/ImageSharp/tree/font-render

### some shinies for people
![newline](https://cloud.githubusercontent.com/assets/166440/21280532/6b44fc5a-c3de-11e6-9583-4c04715280d7.png)
![simple](https://cloud.githubusercontent.com/assets/166440/21280533/6b467e90-c3de-11e6-9712-39b6d03e77e3.png)

**Comment by tocsoft** [comment]
@prepare Yeah I noticed, What I've done for my prototype is just pull in the `PixelFarm.OpenType` netstandard project directly and but I retargeted at netstandard1.1 (which works fine as it doesn't actualy have any dependencies that are not available) and added the second net45 target so that it played nice with the rest of the ImageSharp project.

**Comment by tocsoft** [comment]
@prepare i'm guessing you've not got the OpenType project up as a nuget package or anything? if not then I think i'm just going to have to pull in the code directly (with attribution) and have it live inside the ImageSharp codebase but that'll just make it more difficult to pull in the newest updates when ever you make changed.... some food for thought I think.

**Comment by tocsoft** [comment]
I think i'm doing something dodgy with closing out the glyphs at the moment, i'm pretty sure those `o`s aren't supposed to have there edges cut off like that.

**Comment by JimBobSquarePants** [comment]
@dlemstra I think splitting up the library is still a wise idea. I just need to get my head around the build/publish/deployment process with correct versioning etc. @Jeavon might be able to help there.

@tocsoft @prepare I've deliberately left the rest of the library supporting streams only to allow support for netstandard1.1 Is this going to cause problems?

**Comment by tocsoft** [comment]
@JimBobSquarePants nope the core library doesn't really need to target 1.6 I have it compiling targeting 1.1

**Comment by JimBobSquarePants** [comment]
Great stuff!
