### ISSUE TITLE
Add additional Shapes for drawing.

### ISSUE THREAD

**Issue by tocsoft** [JimBobSquarePants/ImageSharp#39]
Add support for the following shapes

- [x] Rectangle/Square
- [ ] Ellipse/Circle
- [ ] Regular 'X' sided shapes

There are 2 path to follow adding these the optimised or unoptimised route;
 - **unoptimised** : convert the shape to simple linear path/point array and proxy down to the generic `Polygon` class to handle.
 - **optimised** : create entirely custom logic for all aspects of `IShape` and `IPath` required.

You are required to convert down to a point array anyway for things like `ComplexPolygon` to work thus its probably worth doing these as 2 passes;

- **First pass** : Simplify the higher level polygon down a simple Linear path of control points and proxy the heavy lifting onto `Polygon` (which is built for arbitrary shaped polygons).
- **Second Pass** : Optimise the `IShape` and `IPath` methods/properties to avoid `Polygon` as use shape specific logic that can be calculated more efficiently.

**Comment by tocsoft** [comment]
The library already has classes/structs for `Rectangle` and `Ellipse` do we want to expand these by letting them implement `IShape` and push the logic down there? or should we create new classes `RectangularPolygon` and `ElipticalPolygon` which take an `Rectangle` and `Ellipse` as constructor args?

If we go for the second option the we would need/want to provide override extension methods that can take the  struct versions and internally convert them to the polygon versions.

My vote would be for option 2 creating `RectangularPolygon` and `ElipticalPolygon` but just after some opinions.

**Comment by dlemstra** [comment]
My vote would also be for option 2 because we might add extra stuff that is only for drawing.

**Comment by JimBobSquarePants** [comment]
Agreed. Option 2 would be best. I'd like to keep the original rectangle as is and use it simply for expressing an area of interest. I might even drop the original Ellipse as I'm not sure it's being used anywhere.

**Comment by tocsoft** [comment]
Shape are now handled by https://github.com/SixLabors/Shapes thus new primitive shapes should be requested over there.

Additionally, Ellipse/Circle, Regular 'X' sided shapes do now exist.
