### ISSUE TITLE
Fix StyleCop/compiler warnings 

### ISSUE THREAD

**Issue by olivif** [JimBobSquarePants/ImageSharp#48]
Hey everyone! I've been working on getting rid of our build warnings - stylecop and compiler. 

There are 3 categories of warnings left, and I need your help on deciding how to fix those 😄 

**1. SA1649 - File name must match first type name (4)**
This is happening for all classes where we have a generic version and a regular version which share the same name - Brushes, ImageBrush, etc. and we use the convention of ```{name}`{numberOfTypes}.cs``` for the file name. 
The options I see are:
* keep the convention and ignore the warning for this specific case
* get rid of the convention and rename the generic and non generic versions 

I would personally like a better distinction between the T and non T versions, and that would also help with the readability of the code. 

**2. SA1401 - Field must be private (4)**

This is happening in `JpegDecoderCore` only, where we have some internal fields, like below.

```cs
        /// <summary>
        /// The byte buffer.
        /// </summary>
        internal Bytes Bytes;
```
This is a maintainability [rule](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1401.md) - the best practice is to keep all fields to private, and if anything needs to be exposed it should be done via properties. 

Should we change these fields to properties? I'm not very familiar with this code so I'm hoping you will have more reasons for one option or the other. 

**3. CS0219 - The variable <> is assigned but its value is never used (4)**

This is in the test project in `ReferenceImplementations`. r0 and r4 variables are never used. The fix to remove them is trivial, but I was wondering if them not being used is actually intentional.

**Comment by tocsoft** [comment]
I would personally just rename the generic files (and header) to the style StyleCop wants rather than fighting with it.
I.E. Just rename ``Brushes`2.cs`` to` Brushes{TColor,TPacked}.cs`.

**Comment by JimBobSquarePants** [comment]
@olivif Nice work!

>1. SA1649 - File name must match first type name (4)

I'm up for renaming to the explicit generic version. I just used the current naming on a whim as I was refactoring the brushes. 

>2. SA1401 - Field must be private (4)

If it's not references anywhere outside the class make it a private field, otherwise a property.

>3. CS0219 - The variable <> is assigned but its value is never used (4)

If they're not used it's an oversight and the variables should never be assigned.

Of course run the tests to make sure nothing breaks 😸

**Comment by olivif** [comment]
thanks @JimBobSquarePants! 😄 makes sense! will see what I can do.
