### ISSUE TITLE
Support of 8-bit images

### ISSUE THREAD

**Issue by Sergey-Terekhin** [JimBobSquarePants/ImageSharp#55]
Does Image class support 8-bit grayscale images? I mean read, write and convert from other color depths

**Comment by JimBobSquarePants** [comment]
Yeah, there's no reason why it couldn't Several of the image formats support reading and writing grayscale images. Storing the image in grayscale would be as simple as implementing an `IPackedPixel` format. 

It might be an idea to add a built in one actually.

**Comment by paolofulgoni** [comment]
@JimBobSquarePants does the idea of including an 8-bit grayscale pixel format still make sense?

**Comment by merijndejonge** [comment]
I'm new to ImageSharp. Could someone explain to me how I would implement IPackedPixel to support 8-bit grayscale?
Thanks a lot!

**Comment by antonfirsov** [comment]
@merijndejonge as a start, I suggest to check out the [related piece of docs](https://docs.sixlabors.com/articles/ImageSharp/PixelFormats.html). (Note: `IPackedPixel` has been replaced with `IPixel<TSelf>`.)

After checking it out, feel free to ask further questions on our [gitlab channel](https://gitter.im/ImageSharp/General), you will get answers much faster there.
