### ISSUE TITLE
Common .NET 4.6 Sandbox project for performance profiling

### ISSUE THREAD

**Issue by antonfirsov** [JimBobSquarePants/ImageSharp#66]
Most of our discussions are happening below separate issue/PR topics now. With the current team activity it seems to be more efficient to me, so I decided to open an issue for this topic, hope it's fine.

I think if we want a performance-aware team, everyone should (must!) be able to profile code. We can't wait for better netcore tooling, we need it now! 
It's actually very easy with a classic .NET project referencing ImageSharp as a .NET 4.6 dll. With MSBUILD `<Link>` [it's possible](https://github.com/antonfirsov/ImageSharp/blob/jpeg-optimizations-experimental/tests/ImageSharp.Tests46/ImageSharp.Tests46.csproj) to construct such a project adding just ~5 files!

Why don't have it on the common master branch? :)

**Comment by antonfirsov** [comment]
@JimBobSquarePants any initial, quick feedback? :)

**Comment by tocsoft** [comment]
👍 go for it.

**Comment by antonfirsov** [comment]
I would wait for the outcome of @JimBobSquarePants -s fight against VS2017.

**Comment by JimBobSquarePants** [comment]
VS2017 won't be happening anytime soon. I just uninstalled it. Carry on....
