### ISSUE TITLE
How to configure my project to download from myget?

### ISSUE THREAD

**Issue by mateusleonardi** [JimBobSquarePants/ImageSharp#67]
Hello,

Could you help me please?

I want to use your package in my project but I don't know how to set my project to download packages from MyGet gallery.

I'm using Visual Studio 2015 but my server is linux so it's necessary my server be able to download your package using "dotnet restore" from the linux.

Thanks in advance.

**Comment by mateusleonardi** [comment]
I tried to run it with ASP .NET Core 1.1.0 and I couldn't.

Is it possible to upgrade the asp .net core for this project?

How could I do that?

Thanks in advance.

**Comment by JimBobSquarePants** [comment]
Hi @mateusleonardi 

Have you added the MyGet feed to your project? Follow the link from the [Readme](https://github.com/JimBobSquarePants/ImageSharp#installation) and click "Connect to feed" on the gallery page.

https://www.myget.org/F/imagesharp/api/v3/index.json

>I'm using Visual Studio 2015 but my server is linux so it's necessary my server be able to download your package using "dotnet restore" from the linux. 

I don't understand what you mean. You wouldn't use `dotnet restore` on your linux server, there should be no project files there only your build/deployment output.

>I tried to run it with ASP .NET Core 1.1.0 and I couldn't.
Is it possible to upgrade the asp .net core for this project?

You're doing something wrong there. I can do this no problem without any changes. Is your project.json file correct?

![imagesharp-asp](https://cloud.githubusercontent.com/assets/385879/21558116/31daf4fa-ce89-11e6-8380-ba168b5cc461.png)

Could you do me a favour and in the future use the [Gitter Chatroom](https://gitter.im/ImageSharp/General) for general questions. The issue tracker is primarily for issues only. 

Cheers

James
