### ISSUE TITLE
some resized images are in the wrong orientation

### ISSUE THREAD

**Issue by dj-nitehawk** [JimBobSquarePants/ImageSharp#78]
i've been trying to resize (with cropping) some images to a fixed width of 350 and height of 150 with the following code. 

    using (var output = new FileStream("output.jpg", FileMode.Create))
    {
        Image image = new Image(file.OpenReadStream()); //file is a IFormFile object

        image.Resize(new ImageSharp.Processing.ResizeOptions()
        {
            Mode = ImageSharp.Processing.ResizeMode.Crop,
            Size = new Size(350, 150)
        }).SaveAsJpeg(output, 90);

    }

some of the resulting images are 150 wide and 350 height. which is not the result i'm expecting.

how do i get the resulting image to be 350 wide and 150 height no matter what orientation the source image is in?

using `1.0.0-alpha1-00038` from myget with .net core web api project.

some stats:

1.) source image 640w X 1136h => results in 350w X 150h [correct]
2.) source image 750w X 1334h => results in 350w X 150h [correct]
3.) source image 1334w X 750h => results in 150w X 350h [wrong]
4.) source image 960w X 1280h => results in 150w X 350h [wrong]
5.) source image 2448w X 3264h => results in 150w X 350h [wrong]

what's weird is that if i open one of the [wrong] images above in photoshop and export as jpg, imagesharp manages to produce the correct result.

check [this zip file](https://dl.dropboxusercontent.com/u/4759948/images.zip) for a sample image that fails. and also the photoshop exported version of the same image which works.

**Comment by dlemstra** [comment]
You could call `.AutoOrient` on the image before you resize it. This will rotate the image to the "correct" orientation.

**Comment by tocsoft** [comment]
@dj-nitehawk  I can confirm, based on your test image, that `.AutoOrient()` is all you need to do to fix your issue.

**Comment by JimBobSquarePants** [comment]
@dlemstra @tocsoft That answer does the trick but 

@dj-nitehawk It's best to also explain why ImageSharp is actually doing the right thing without `AutoRotate()`

ImageSharp is actually correctly resizing those images.

Jpeg files have specific values in something called the Start of Frame marker which defines the width and height of the image. ImageSharp, like any other library (e.g System.Drawing) will read those values to determine the correct dimensions and layout of the byte array to store that image data. 

The EXIF metadata contained within the image is additional, unrelated data that is sometimes used to determine how the image is displayed (i.e. rotation).

This data does not determine how the width and height of an image is calculated. Software like Photoshop might (I haven't tested) present the image in a rotated fashion with the dimensions swapped to make it less confusing for the end user but a graphics library will not.

I hope that makes sense

**Comment by dj-nitehawk** [comment]
thanks guys! 

`.AutoOrient()` does the job perfectly...

appreciate the super-fast support :-)
