### ISSUE TITLE
NotSupportedException: Image cannot be loaded

### ISSUE THREAD

**Issue by vaindil** [JimBobSquarePants/ImageSharp#80]
I'm using 1.0.0-alpha1-00048, .NET Core 1.1.0. I'm unable to load any images whatsoever. Every single image I try returns this exception:

> NotSupportedException: Image cannot be loaded. Available formats:
> -ImageSharp.Formats.PngFormat
> -ImageSharp.Formats.JpegFormat
> -ImageSharp.Formats.GifFormat

I'm [manually checking](https://stackoverflow.com/a/8755028/1672458) the stream to ensure it's a valid image, and I know they're being handled properly because I ultimately upload to AWS and the files are exact matches. Not sure what's going on. I can provide sample images if you'd like, but it's happening with every one of the 10+ images I tried (random images that happen to be on my computer, all either .jpg, .png, or .gif).

Code:

```csharp
[HttpPost]
public async Task<IActionResult> Upload(IFormFile image)
{
    var verify = UploadHelpers.VerifyImageUpload(image);
    if (verify != string.Empty)
        return BadRequest(verify.ToGenericErrorJson());

    Image result = null;

    using (var stream = new MemoryStream())
    {
        await image.CopyToAsync(stream);

        UploadHelpers.StripExif(stream);

        result = await _imgSvc.UploadImageAsync(stream, User.Id,
            Path.GetExtension(image.FileName).ToLower(), image.ContentType);
    }

    // do some stuff

    return Ok();
}

public static void StripExif(Stream stream)
{
    // exception thrown here
    var image = new Image(stream);

    // strip Exif tags
}
```

**Comment by JimBobSquarePants** [comment]
Are you using the various config packages listed in the [readme](https://github.com/JimBobSquarePants/ImageSharp#packages)?

**Comment by vaindil** [comment]
Yes, I have those installed. Am I stupid and am supposed to be referencing them somehow?

**Comment by tocsoft** [comment]
@JimBobSquarePants based on the error message it looks like we are loading the Formats (otherwise they wouldn't have been listed in the error) but we are somehow failing to decode them.

Looks like only ImageSharp.Formats.PngFormat, ImageSharp.Formats.JpegFormat, and ImageSharp.Formats.GifFormat have been loaded so unless the image is actually turning out to be a bmp it doesn't look like a simple configuration/referencing issue.

**Comment by JimBobSquarePants** [comment]
Good point @tocsoft 

```
public static void StripExif(Stream stream)
{
    // exception thrown here
    var image = new Image(stream);

    // strip Exif tags
}
```

 @vaindil  It looks like you are not resetting the stream after you are copying to it. Try setting the position to 0 before creating the image.

**Comment by vaindil** [comment]
@JimBobSquarePants Ugh, that was the problem. I added `stream.Seek(0, SeekOrigin.Begin);` above the existing code and now it works. Thank you, I'm so sorry!

**Comment by JimBobSquarePants** [comment]
Don't worry about it! We're all learning. :smile:
