### ISSUE TITLE
net45-profile builds depend on System.Numerics.Vectory 4.1.1.0 from CoreFX

### ISSUE THREAD

**Issue by ibauersachs** [JimBobSquarePants/ImageSharp#81]
The binary packages targeting the full .NET framework (net45) depend on System.Numerics.Vectors 4.1.1.0, which is from the CoreFX. While it's possible to work around that with an assembly redirect, it shouldn't be necessary.

**Comment by JimBobSquarePants** [comment]
As far as I'm aware NET 4.6.1 was the first version to have vectors baked in. 4.5 requires the reference. Will double check.

**Comment by ibauersachs** [comment]
Yes, you're right, I was working on modifying the project definitions. Would you be interested in a PR that supports net461 as an additional target?

**Comment by JimBobSquarePants** [comment]
Absolutely! I hate all the project target stuff so that would really help.
