### ISSUE TITLE
Could not load signature of ImageSharp.Image`1[TColor]:To due to: Could not load file or assembly or one of its dependencies.

### ISSUE THREAD

**Issue by nah0y** [JimBobSquarePants/ImageSharp#89]
Hello!
Awesome project you have here! Can't wait to have a first release :)

I'm on OSX, and I'm using MonoDevelop on a project compiled against Mono / .NET 4.5.
I downloaded every DLL (in the net45 folder) from the pre-releases here https://www.myget.org/gallery/imagesharp except the ImageSharp.Drawing which I won't use.
Everything compiles but when I try to call a method I got this error message:
"Could not load signature of ImageSharp.Image`1[TColor]:To due to: Could not load file or assembly or one of its dependencies."

Any idea of what could be causing this?

Thanks!

**Comment by tocsoft** [comment]
As it sounds like you aren't using nuget for you dependencies and thus missed one of your package depndencies, you will need to make sue you load in `ImageSharp`s nuget dependencies yourself. 

You can see our dependencies on myget by heading over to the core 'ImageSharp' package (https://www.myget.org/feed/imagesharp/package/nuget/ImageSharp) and hit up the **Dependencies** tab and work your way down the chain.

**Comment by nah0y** [comment]
Thanks! I'll try in a few hours to get that with nuget (Previously, I just downloaded the package and renamed it to zip to extract the DLLs).
I can't add the required dependencies manually in MonoDevelop as they are not listed as available. Only System.Numerics is :/

**Comment by JimBobSquarePants** [comment]
>(Previously, I just downloaded the package and renamed it to zip to extract the DLLs).

@nah0y That's a very odd way to add a dependency to a project. It completely bypassess all the usefulness that Nuget brings. MonoDevelop uses Nuget package manager yeah? 

@tocsoft I was experimenting with VS2017 again last night and the references it setup and pulled in were different to what we have. I wonder whether we are doing something wrong?

**Comment by nah0y** [comment]
Well, I'm a Unity 3D developer, so never really used NuGet to get things :/
Also, I never understood, why go through NuGet to deliver things, and not directly give a dll (or multiple dlls) containing everything?

Plus, I'm on a Mac, and nuget on a Mac is not as easy to use as on Windows :)

**Comment by nah0y** [comment]
I tried to install it using Visual Studio Community 2015, everything was doing great until: 

> Failed to add reference. The package 'ImageSharp' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by JimBobSquarePants** [comment]
@nah0y Thanks for that information. I'll have a look (Time to dig out my wife's MacBook and pretend I know how to use it 😄 ) I suspect we just have to add configuration for another runtime dependency tree for Mono.

Nuget is the way to go. It allows handling dependencies in an elegant way which allows very incremental version control on all dependencies. + you don't want to be checking in dll's into your source control as they just use up space.

**Comment by tocsoft** [comment]
The missing dependency issue could be related to nuget.exe versions i'm pretty sure you have to be running a version on nuget > 3.4. I believe mono ships with its own version of nuget but its a custom patched 2.8.4 build you should now be able to use the latest nuget.exe from nuget .org on linux/mac using mono. (I believe its now mono compatible).

**big caveat** I am a windows dev on a windows machine and I haven't had to touch too much mac/linux/mono stuff outside of fighting with a build servers. I also reserve the right to be completly wrong 😁

**Comment by tocsoft** [comment]
Looks like our net45 defiantly has dependency issues.. I have been able to reproduce. Not sure what the fix is yet.

**Comment by JimBobSquarePants** [comment]
@tocsoft Ok, I'll see what I can do.

**Comment by tocsoft** [comment]
**Repoduction steps:**

1. in VS 2015 create new .net 4.5.2 console application
2. Add `ImageSharp.Formats.Jpeg` nuget package
3. Try building

**Expected result**
a running console application where I can open/write images

**Actual results**
Error showing
`Failed to add reference. The package 'ImageSharp' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.`

**Comment by nah0y** [comment]
> The missing dependency issue could be related to nuget.exe versions i'm pretty sure you have to be running a version on nuget > 3.4. I believe mono ships with its own version of nuget but its a custom patched 2.8.4 build you should now be able to use the latest nuget.exe from nuget .org on linux/mac using mono. (I believe its now mono compatible).

@tocsoft I downloaded nuget.exe directly from the nuget website, not using one that was maybe somewhere on my mono installation :)

@JimBobSquarePants And yes you're right, in fact I'm targeting Mono from my Mac and it's not working :)
On a Windows machine everything's ok, but it's not on a Mac.

I would love to help to debug this if I can, please just tell me what to do.
But if you have a Mac and install MonoDevelop you should have the same issues.

**Comment by JimBobSquarePants** [comment]
@nah0y Give 1.0.0-alpha1-00073 a go. It works for me on both NET45 and NET46 projects

**Comment by nah0y** [comment]
Yaay this fix everything! It's now working on OS X :)
Thanks a lot!
