### ISSUE TITLE
Interlacing is not supported

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#9]
_From @Bartmax on May 6, 2016 4:25_

When using a Png file I get this error:

```
ImageProcessorCore.ImageFormatException: Interlacing is not supported
```

some png works but some doesn't.

The code is here:
https://github.com/JimBobSquarePants/ImageProcessor/blob/abbf63f863635d4df1a04d322eccd425db7e82db/src/ImageProcessorCore/Formats/Png/PngDecoderCore.cs#L385

What does this mean? is this a limitation of the library or am I doing something wrong or a bug?

_Copied from original issue: JimBobSquarePants/ImageProcessor#379_

**Comment by JimBobSquarePants** [comment]
Hi @Bartmax 

It means exactly that. Png files can be interlaced but it is strongly recommended not to do that as it hurts compression, increasing filesize. 

See 

- http://stackoverflow.com/a/14124340/427899
- http://blog.codinghorror.com/getting-the-most-out-of-png/ 

Interlaced png files are generally uncommon so I haven't gone out of my way to support them cos it's complex. I could maybe add support in the future though as there is [good reference material](https://github.com/leonbloy/pngcs/blob/master/Hjg.Pngcs/PngDeinterlacer.cs) to base my code on so if you could share a failing image that would be really useful.

**Comment by JimBobSquarePants** [comment]
_From @Bartmax on May 6, 2016 4:39_

Thanks for the fast reply.

Here is a sample file that is failing. I have 3 out of 10 that seems to be interlaced :(

![546ce378-2bcf-4604-8338-91d9065727c4](https://cloud.githubusercontent.com/assets/3386797/15064484/31fc702c-132b-11e6-8bf9-1500c51e43f1.png)

**Comment by JimBobSquarePants** [comment]
No worries. I'll branch off and try to tinker with it. Fingers crossed it's not too difficult.

**Comment by JimBobSquarePants** [comment]
This is tricky stuff...

I've been looking at the spec and also the Golang implementation.

https://www.w3.org/TR/PNG/
https://golang.org/src/image/png/reader.go

Reading up it looks like I need to decode each scanline 8 times which will require some significant refactoring here. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/7d28a87716e4b7c2dea73bc0fb804873d30372f6/src/ImageProcessorCore/Formats/Png/PngDecoderCore.cs#L242

I could really do with someone who has done this before stepping up and adding the code.

**Comment by JimBobSquarePants** [comment]
_From @MarcosMeli on August 29, 2016 16:28_

@JimBobSquarePants 
Just a little question here. There is an option to use the .Net native image load implementation and convert the resulting Bitmap to the format you need ?

ie. try to use custom decode for the pngs but, if interlaced, so use Bitmap constructor: https://msdn.microsoft.com/en-us/library/z7ha67kw(v=vs.110).aspx

Thanks

**Comment by JimBobSquarePants** [comment]
_From @dlemstra on August 29, 2016 16:59_

The library should build on .NET Core where we don't have the Image class of System.Drawing. Adding it to the encoder should be the way to go.

**Comment by JimBobSquarePants** [comment]
_From @MarcosMeli on August 29, 2016 17:50_

@dlemstra Thanks for clarification, I understand now.

**Comment by JimBobSquarePants** [comment]
Had a crack at this and I'm so close. I'm reading the stream fine without error but something isn't right after. It looks like my offset calculation is wrong. Could someone have a look?

![splash-interlaced](https://cloud.githubusercontent.com/assets/385879/20856847/e3bbe1a0-b96e-11e6-949d-aec1d14bb301.png)

**Comment by JimBobSquarePants** [comment]
Ok @Bartmax so I'm almost there with this. 

I can decode your rgb image perfectly now and my rgba image also. I have one test image though (rgb 8x8) that is showing a two pixel error and I don't know why. If anyone reading could have a look that would be great.

Here's your image decoded then encoded in non-interlaced mode.

![interlace-2](https://cloud.githubusercontent.com/assets/385879/20863812/284cc0aa-ba2d-11e6-86b9-5351ad1347c6.png)

**Comment by Bartmax** [comment]
So the only problem is with rgb 8x8 image ? Can you point me to the code? is there a failing test? I have no experience on image manipulation but I will be glad to help and try to solve this. Maybe we can take the converstaion offline to slack so you can guide me in how to approach the problem?

**Comment by Bartmax** [comment]
played with the code, I see some errors (or I think are errors) on the tests, see:
 * https://github.com/Bartmax/ImageSharp/commit/5cce27f1f76a3797e141cb071440ec40e013c461
 * https://github.com/Bartmax/ImageSharp/commit/2e7b0e118ab93bcf849eac25b6a279c524e87d28
 * https://github.com/Bartmax/ImageSharp/commit/f2a84e99cd59946bcbd1099c2c96aa659362d0a9

I have no idea if this has or not anything to do with the interlace thing and need some guidance on how to test if it works with your `interlaced.png` (rgba 8x8) file.

**Comment by JimBobSquarePants** [comment]
Thanks for highlighting the failing tests, not sure how that slipped through.

I managed to fix the decoder! Turns out I wasn't clearing an array at the correct time.

**Comment by Bartmax** [comment]
@JimBobSquarePants well excellent news!! hope to be more useful next time 😄

**Comment by JimBobSquarePants** [comment]
Don't worry, you were useful 👍 

I've merged my branch and you should see a shiny new working build now.
