### ISSUE TITLE
Error after upgrading to 1.0.0-alpha1-00071

### ISSUE THREAD

**Issue by eat-sleep-code** [JimBobSquarePants/ImageSharp#93]
I have the following code.   

```
using ImageSharp;
using ImageSharp.Formats;
using ImageSharp.Processing;
using Microsoft.AspNetCore.Http;
using System;
using System.IO;

namespace Brand.Extensions
{
	public class ImageExtensions 
    {	
		public byte[] CreateThumbnail(IFormFile sourceFile, int targetWidth, int targetHeight)
		{	
			MemoryStream outputStream = new MemoryStream();
			try
			{
				using (Stream sourceStream = sourceFile.OpenReadStream())
				{
					Image image = new Image(sourceStream);
					image.HorizontalResolution = 72;
					image.VerticalResolution = 72;
					PngEncoder pngEncoder = new PngEncoder();
					if (image.Width > image.Height) /* Landscape  */
					{
						image.Resize(targetWidth, (targetWidth / image.Width) * targetHeight).Crop(targetWidth, targetHeight).Save(outputStream, pngEncoder);
					}
					else /* Portrait or Square */
					{
						image.Resize((targetHeight / image.Height) * targetWidth, targetHeight).Crop(targetWidth, targetHeight).Save(outputStream, pngEncoder);
					}
				}
			}
			catch (Exception ex)
			{
				new LoggerExtensions().LogException(ex, "Brand Central Station: Image Extensions");
			}
			return outputStream.ToArray();
		}
	}
}
```

After upgrading to 1.0.0-alpha1-00071 the following errors are being thrown:

> 'Image' does not contain a definition for 'Resize' and no extension method 'Resize' accepting a first argument of type 'Image' could be found (are you missing a using directive or an assembly reference?)

> The type or namespace name 'BicubicResampler' could not be found (are you missing a using directive or an assembly reference?)

> The type or namespace name 'PngEncoder' could not be found (are you missing a using directive or an assembly reference?)

It appears there has been some refactoring since the old version I was using, but I am having trouble figuring out how to proceed.

**Comment by tocsoft** [comment]
You are also going to want to add a dependencies on `ImageSharp.Processing`  *Contains methods like Resize, Crop, Skew, Rotate*

Also you will want to add some codecs as required;
- `ImageSharp.Formats.Jpeg` 
- `ImageSharp.Formats.Png`
- `ImageSharp.Formats.Gif` 
- `ImageSharp.Formats.Bmp`

**Comment by JimBobSquarePants** [comment]
@eat-sleep-code Can you please stop deleting the issue template. It's there for a reason.

**Comment by JimBobSquarePants** [comment]
@eat-sleep-code Also...

https://github.com/JimBobSquarePants/ImageSharp#packages

>The ImageSharp library is made up of multiple packages, to make ImageSharp do anything useful you will want to make sure you include at least one format as a dependency otherwise you will not be able to save/load any images.
